<?php

/**
 * @file
 * Displays locations on a map.
 * for Drupal 6
 * using version 3 googlemaps API
 */

define('GETLOCATIONS_PATH', drupal_get_path('module', 'getlocations'));

/**
 * Implementation of hook_help().
 */
function getlocations_help($path, $arg) {
  switch ($path) {
    case 'admin/help#getlocations':
      $output = '<p>'. t('Displays locations on a map.') .'</p>';
      return $output;
  }
}

/**
 * Implementation of hook_init().
 */
function getlocations_init() {
  module_load_include('inc', 'getlocations', 'getlocations.theme');
  if (module_exists('colorbox')) {
    $getlocations_colorbox = variable_get('getlocations_colorbox', array(
      'enable' => 0,
      'width' => 600,
      'height' => 600,
    ));
    $settings = array('getlocations_colorbox' => $getlocations_colorbox);
    drupal_add_js(GETLOCATIONS_PATH .'/js/getlocations_colorbox.js');
  }
  else {
    $settings = array('getlocations_colorbox' => array('enable' => 0));
  }
  drupal_add_js($settings, 'setting');

}

/**
 * Implementation of hook_perm().
 */
function getlocations_perm() {
  return array('access getlocations', 'access user getlocations');
}

/**
 * Implementation of hook_menu().
 */
function getlocations_menu() {
  $items = array();

  $items['admin/settings/getlocations'] = array(
    'title' => 'Get locations',
    'description' => 'Configure Get locations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('getlocations_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'getlocations.admin.inc',
  );

  // getlocations/node/$nid    # show all location on one node
  $items['getlocations/node/%getlocations_id'] = array(
    'title' => 'Get locations',
    'access callback' => 'getlocations_access_location',
    'page callback' => 'getlocations_nodemap',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
  );

  // getlocations/user/$uid    # show all locations for a user
  $items['getlocations/user/%getlocations_id'] = array(
    'title' => 'Get locations',
    'access callback' => 'getlocations_access_user_location',
    'page callback' => 'getlocations_usermap',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
  );

  // getlocations/users    # show all locations for all users
  $items['getlocations/users'] = array(
    'title' => 'View all user locations',
    'access callback' => 'getlocations_access_user_location',
    'page callback' => 'getlocations_usersmap',
    'type' => MENU_CALLBACK,
  );

  // getlocations/type/$type     # show all locations of nodes of content-type machine name
  $items['getlocations/type/%getlocations_type'] = array(
    'title' => 'Get locations',
    'access callback' => 'getlocations_access_location',
    'page callback' => 'getlocations_typemap',
    'page arguments' => array(2, 3, 4),
    'type' => MENU_CALLBACK,
  );

  // getlocations/lids/1,2,3,4    # show lids
  $items['getlocations/lids/%getlocations_cdints'] = array(
    'title' => 'Get locations',
    'access callback' => 'getlocations_access_location',
    'page callback' => 'getlocations_lids',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
  );

  // getlocations/nids/1,2,3,4    # show nids locations
  $items['getlocations/nids/%getlocations_cdints'] = array(
    'title' => 'Get locations',
    'access callback' => 'getlocations_access_location',
    'page callback' => 'getlocations_nids',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
  );

  // getlocations/info/lid    # ajax callback to fetch an address
  $items['getlocations/info'] = array(
    'page callback' => 'getlocations_info',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['getlocations_box'] = array(
    'title' => 'Get locations',
    'access arguments' => array('access getlocations'),
    'page callback' => 'getlocations_box',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * menu placeholder functions
 */
function getlocations_id_load($arg) {
  return (is_numeric($arg) && $arg > 0 ? $arg : FALSE);
}

/**
 * Check that the node type exists
 *
 */
function getlocations_type_load($arg) {
  $result = db_query("SELECT name FROM node_type WHERE type='%s'", array($arg));
  $row = db_fetch_array($result);
  return ((isset($row['name']) && $row['name']) ? $arg : FALSE);
}

function getlocations_cdints_load($arg) {
  $arr = explode(',', $arg);
  foreach ($arr AS $a) {
    if (! is_numeric($a) || $a < 1 ) {
      return FALSE;
    }
  }
  return $arg;
}

/**
 * menu access functions
 */
function getlocations_access_location() {
  if (module_exists('location') && user_access('access getlocations') && (module_exists('location_node') || module_exists('location_cck'))) {
    return TRUE;
  }
  return FALSE;
}

function getlocations_access_user_location() {
return true;
  if (module_exists('location') && user_access('access getlocations') && user_access('access user getlocations') && module_exists('location_user')) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Menu callback
 *
 * @param int $nid
 *
 * @return
 *   Returns a map of locations of a node
 *
 */
function getlocations_nodemap($nid) {
  $vid = getlocations_get_vid($nid);
  $locations = location_load_locations($vid);
  $node = node_load($nid);
  $newlocations = array();
  $latlons = array();
  $minmaxes = array('minlat' => 0, 'minlon' => 0, 'maxlat' => 0, 'maxlon' => 0);
  $ct = 0;
  if (count($locations)) {
    // we should loop over them and dump bummers with no lat/lon
    foreach ($locations AS $key => $location) {
      if (getlocations_latlon_check($location['latitude'] . ',' . $location['longitude']) ) {
        $minmaxes = getlocations_do_minmaxes($ct, $location, $minmaxes);
        $ct++;
        $newlocations[] = $location;
        $latlons[] = $location['latitude'] . ',' . $location['longitude'] . ',' . $location['lid'] . ',' . $location['name'];
      }
    }
  }
  if ($ct < 2 ) {
    unset($minmaxes);
    $minmaxes = '';
  }

  drupal_set_title(t('View @t locations', array('@t' => $node->title)));

  // all in $newlocations
  return getlocations_setlocations($newlocations, $latlons, $minmaxes, 'node', $node);

}

/**
 * Menu callback
 *
 * @param int $uid
 *
 * @return
 *   Returns a map of locations of a user
 *
 */
function getlocations_usermap($uid) {
  if (module_exists('location_user')) {
    $locations = location_load_locations($uid, 'uid');
    $account = user_load(array('uid' => $uid));
    $newlocations = array();
    $latlons = array();
    $minmaxes = array('minlat' => 0, 'minlon' => 0, 'maxlat' => 0, 'maxlon' => 0);
    $ct = 0;
    if (count($locations)) {
      // we should loop over them and dump bummers with no lat/lon
      foreach ($locations AS $key => $location) {
        if (getlocations_latlon_check($location['latitude'] . ',' . $location['longitude']) ) {
          $minmaxes = getlocations_do_minmaxes($ct, $location, $minmaxes);
          $ct++;
          $newlocations[] = $location;
          $latlons[] = $location['latitude'] . ',' . $location['longitude'] . ',' . $location['lid'] . ',' . $location['name'];
        }
      }
    }
    if ($ct < 2 ) {
      unset($minmaxes);
      $minmaxes = '';
    }

    drupal_set_title(t('View user @t locations', array('@t' => $account->name)));

    // all in $newlocations
    return getlocations_setlocations($newlocations, $latlons, $minmaxes, 'user');
  }
}

/**
 * Menu callback
 *
 *
 * @return
 *   Returns a map of locations of all the users
 *
 */
function getlocations_usersmap() {

  if (module_exists('location_user')) {
    $newlocations = array();
    $latlons = array();
    $minmaxes = array('minlat' => 0, 'minlon' => 0, 'maxlat' => 0, 'maxlon' => 0);
    $result = db_query("SELECT uid FROM users WHERE status=1");
    $ct = 0;
    while ($row = db_fetch_array($result)) {
      $uid = $row['uid'];
      $locations = location_load_locations($uid, 'uid');
      if (count($locations)) {
        // we should loop over them and dump bummers with no lat/lon
        foreach ($locations AS $key => $location) {
          if (getlocations_latlon_check($location['latitude'] . ',' . $location['longitude']) ) {
            $minmaxes = getlocations_do_minmaxes($ct, $location, $minmaxes);
            $ct++;
            $newlocations[] = $location;
            $latlons[] = $location['latitude'] . ',' . $location['longitude'] . ',' . $location['lid'] . ',' . $location['name'];
          }
        }
      }
    }

    if ($ct < 2 ) {
      unset($minmaxes);
      $minmaxes = '';
    }
   // all in $newlocations
    return getlocations_setlocations($newlocations, $latlons, $minmaxes, 'users');
  }
}

/**
 * Menu callback
 *
 * @param string $type
 * A location enabled content type
 *
 * @return
 *   Returns a map of locations of all nodes of content-type $type
 *
 */
function getlocations_typemap($type, $loc_key='', $loc_val = '') {
  $newlocations = array();
  $latlons = array();
  $minmaxes = array('minlat' => 0, 'minlon' => 0, 'maxlat' => 0, 'maxlon' => 0);
  $result = db_query("SELECT nid FROM node WHERE type='%s'", array($type));
  $ct = 0;
  while ($row = db_fetch_array($result)) {
    $nid = $row['nid'];
    $vid = getlocations_get_vid($nid);
    $locations = location_load_locations($vid);
    if (count($locations)) {
      // we should loop over them and dump bummers with no lat/lon
      foreach ($locations AS $key => $location) {
        if (getlocations_latlon_check($location['latitude'] . ',' . $location['longitude']) ) {
          if ($loc_key && isset($location[$loc_key])) {
            if (strtolower($location[$loc_key]) != strtolower($loc_val)) {
              continue;
            }
          }
          $minmaxes = getlocations_do_minmaxes($ct, $location, $minmaxes);
          $ct++;
          $newlocations[] = $location;
          $latlons[] = $location['latitude'] . ',' . $location['longitude'] . ',' . $location['lid'] . ',' . $location['name'];
        }
      }
    }
  }
  if ($ct < 2 ) {
    unset($minmaxes);
    $minmaxes = '';
  }
  // all in $newlocations
  return getlocations_setlocations($newlocations, $latlons, $minmaxes, $type);
}

/**
 * Menu callback
 *
 * @param string $lidlist
 * A comma-delimited list of location ids
 *
 * @return
 *   Returns a map of locations.
 *
 */
function getlocations_lids($lidlist) {
  $lidarr = explode(',', $lidlist);
  $locations = array();
  $newlocations = array();
  $latlons = array();
  $minmaxes = array('minlat' => 0, 'minlon' => 0, 'maxlat' => 0, 'maxlon' => 0);
  $ct = 0;

  foreach ($lidarr AS $lid) {
    $locations[] = location_load_location($lid);
  }
  if (count($locations)) {
    // we should loop over them and dump bummers with no lat/lon
    foreach ($locations AS $key => $location) {
      if (getlocations_latlon_check($location['latitude'] . ',' . $location['longitude']) ) {
          $minmaxes = getlocations_do_minmaxes($ct, $location, $minmaxes);
          $ct++;
          $newlocations[] = $location;
          $latlons[] = $location['latitude'] . ',' . $location['longitude'] . ',' . $location['lid'] . ',' . $location['name'];
      }
    }
  }
  if ($ct < 2 ) {
    unset($minmaxes);
    $minmaxes = '';
  }
  // all in $newlocations
  return getlocations_setlocations($newlocations, $latlons, $minmaxes, 'lids');

}

/**
 * Menu callback
 *
 * @param string $nidlist
 * A comma-delimited list of node ids
 *
 * @return
 *   Returns a map of locations.
 *
 */
function getlocations_nids($nidlist) {
  $nidarr = explode(',', $nidlist);
  $locations = array();
  $newlocations = array();
  $latlons = array();
  $minmaxes = array('minlat' => 0, 'minlon' => 0, 'maxlat' => 0, 'maxlon' => 0);
  $ct = 0;

  foreach ($nidarr AS $nid) {
    $vid = getlocations_get_vid($nid);
    $locs = location_load_locations($vid);
    if (count($locs)) {
      foreach ($locs AS $key => $loc) {
        $locations[] = $loc;
      }
    }
  }
  if (count($locations)) {
    // we should loop over them and dump bummers with no lat/lon
    foreach ($locations AS $key => $location) {
      if (getlocations_latlon_check($location['latitude'] . ',' . $location['longitude']) ) {
        $minmaxes = getlocations_do_minmaxes($ct, $location, $minmaxes);
        $ct++;
        $newlocations[] = $location;
        $latlons[] = $location['latitude'] . ',' . $location['longitude'] . ',' . $location['lid'] . ',' . $location['name'];
      }
    }
  }
  if ($ct < 2 ) {
    unset($minmaxes);
    $minmaxes = '';
  }
  // all in $newlocations
  return getlocations_setlocations($newlocations, $latlons, $minmaxes, 'nids');
}

/**
 * Set up javascript settings and map
 */
function getlocations_setlocations($locations, $latlons, $minmaxes='', $type='node', $node = '', $width='', $height='') {
  if (! getlocations_check()) {
    return t('You need to !c first.', array('!c' => l('configure Getlocations', 'admin/settings/getlocations')));
  }
  global $language, $base_url;
  $getlocations_defaults = getlocations_defaults();
  getlocations_setup_map($getlocations_defaults);
  $lla = explode(',', $getlocations_defaults['latlong']);
  $getlocations_settings = array(
    'lat' => $lla[0],
    'lng' => $lla[1],
    'mylocale' => $language->language,
    'zoom'            => $getlocations_defaults['zoom'],
    'maptype'         => $getlocations_defaults['maptype'],
    'controltype'     => $getlocations_defaults['controltype'],
    'mtc'             => $getlocations_defaults['mtc'],
    'baselayers'      => $getlocations_defaults['baselayers'],
    'scale'           => $getlocations_defaults['behavior']['scale'],
    'overview'        => $getlocations_defaults['behavior']['overview'],
    'overview_opened' => $getlocations_defaults['behavior']['overview_opened'],
    'scrollwheel'     => $getlocations_defaults['behavior']['scrollwheel'],
    'trafficinfo'     => $getlocations_defaults['trafficinfo'],
    'bicycleinfo'     => $getlocations_defaults['bicycleinfo'],
    'streetview_show' => $getlocations_defaults['streetview_show'],
    'pancontrol'      => $getlocations_defaults['pancontrol'],
    'panoramio_show'  => $getlocations_defaults['panoramio_show'],
    'poi_show'        => $getlocations_defaults['poi_show'],
    'transit_show'    => $getlocations_defaults['transit_show'],
    'map_marker'      => $getlocations_defaults['map_marker'],
    'minzoom'         => $getlocations_defaults['minzoom'],
    'maxzoom'         => $getlocations_defaults['maxzoom'],
    'nodezoom'        => $getlocations_defaults['nodezoom'],
    'useinfobubble'   => $getlocations_defaults['useinfobubble'],
    'usemarkermanager' => $getlocations_defaults['usemarkermanager'],
    'pansetting'      => $getlocations_defaults['pansetting'],
    'datanum' => count($latlons),
    'latlons' => implode('|', $latlons),
  );
  if (! empty($minmaxes)) {
    $getlocations_settings['minmaxes'] = implode(',', $minmaxes);
  }
  else {
    $getlocations_settings['minmaxes'] = '';
  }

  drupal_add_js(array('getlocations' => $getlocations_settings), 'setting');

  if (empty($width)) {
    $width = $getlocations_defaults['width'];
  }
  if (empty($height)) {
    $height = $getlocations_defaults['height'];
  }

  return theme('getlocations_show', $width, $height, $getlocations_defaults, $type, $node);

}

/**
 * Function to setup the map scripts
 *
 * @param $defaults
 *   Required. the current settings.
 * Sets up the call to googlemaps, css and the relevant getlocations js in html head
 */
function getlocations_setup_map($defaults) {
  global $language;
  // v3 googlemaps API
  $query = array(
    'sensor' => 'false',
    'language' => $language->language,
  );
  $libraries = array();
  if($defaults['panoramio_show']) {
    $libraries[] = 'panoramio';
  }
  // more libraries here

  // load libraries if any
  if (count($libraries)) {
    $query['libraries'] = implode(',', $libraries);
  }
  $gmaplink = '<script src="'. url('http://maps.google.com/maps/api/js', array('query' => $query)) .'" type="text/javascript"></script>';
  drupal_set_html_head($gmaplink);
  drupal_add_css(GETLOCATIONS_PATH .'/getlocations.css');
  drupal_add_js(GETLOCATIONS_PATH .'/js/icons.js');
  drupal_add_js(file_directory_path() . '/js/getlocations_markers.js');
  if ($defaults['usemarkermanager']) {
    drupal_add_js(GETLOCATIONS_PATH .'/js/markermanager.js');
  }
  if ($defaults['useinfobubble']) {
    drupal_add_js(GETLOCATIONS_PATH .'/js/infobubble.js');
  }
  drupal_add_js(GETLOCATIONS_PATH .'/js/getlocations.js');
}

/**
 * Some defaults.
 *
 * @return
 *   Returns the current settings
 */
function getlocations_defaults() {

  $defaults = array(
    'api_version' => 3,
    'width' => '300px',
    'height' => '200px',
    'zoom' => 3,
    'controltype' => 'small',
    'pancontrol' => 1,
    'latlong' => '40,0',
    'maptype' => 'Map',
    'mtc' => 'standard',
    'baselayers' => array(
      'Map' => 1,
      'Satellite' => 1,
      'Hybrid' => 1,
      'Physical' => 1,
    ),
    'behavior' => array(
      'scale' => 0,
      'scrollwheel' => 0,
      'overview' => 0,
      'overview_opened' => 0,
    ),
    'streetview_show' => 0,
    'trafficinfo' => 0,
    'bicycleinfo' => 0,
    'panoramio_show' => 0,
    'poi_show' => 1,
    'transit_show' => 1,
    'map_marker' => 'drupal',
    'minzoom' => 6,
    'maxzoom' => 16,
    'nodezoom' => 12,
    'useinfobubble' => 1,
    'usemarkermanager' => 1,
    'pansetting' => 2,
    'returnlink_page_enable' => 0,
    'returnlink_page_link' => t('Return to Page'),
    'returnlink_user_enable' => 0,
    'returnlink_user_link' => t('Return to User'),
  );

  $getlocations_defaults = variable_get('getlocations_default', array());
  // array_merge deletes things in $defaults that are not in $getlocations_defaults ;-/
  // roll my own
  $newdefaults = array();
  foreach ($defaults AS $k => $v) {
    if (is_array($v)) {
      foreach ($defaults[$k] AS $k1 => $v1) {
        if (isset($getlocations_defaults[$k][$k1])) {
          $newdefaults[$k][$k1] = $getlocations_defaults[$k][$k1];
        }
        else {
          $newdefaults[$k][$k1] = $v1;
        }
      }
    }
    else {
      if (isset($getlocations_defaults[$k])) {
        $newdefaults[$k] = $getlocations_defaults[$k];
      }
      else {
        $newdefaults[$k] = $v;
      }
    }
  }
  return $newdefaults;
}

/**
 * Function to check if the configuration has been done yet
 *
 * @return
 *   Returns true or false
 */
function getlocations_check() {
  $check = variable_get('getlocations_default', 'xxx');
  if ($check == 'xxx') {
    return FALSE;
  }
  return TRUE;
}

/**
 * Function to check a lat,lon string
 *
 * @param string $latlon
 *
 * @return
 *   Returns true or false
 */
function getlocations_latlon_check($latlon) {
  if (! empty($latlon) && preg_match("/[0-9.\-],[0-9.\-]/", $latlon)) {
    $ll = explode(',', $latlon);
    if (isset($ll[0]) && is_numeric($ll[0]) && $ll[0] <> 0 && isset($ll[1]) && is_numeric($ll[1]) && $ll[1] <> 0) {
      return $latlon;
    }
  }
  return FALSE;
}

/**
 * Function to get the vid from node table.
 *
 * @param int $nid
 *
 * @return
 *   Returns vid.
 */
function getlocations_get_vid($nid) {
  $result = db_query('SELECT vid FROM {node} WHERE nid=%d', array($nid));
  $row = db_fetch_array($result);
  return (isset($row['vid']) && $row['vid'] ? $row['vid'] : FALSE);
}

function getlocations_get_nid_from_lid($lid) {
  if ($lid) {
    $result = db_query('SELECT nid FROM location_instance WHERE lid=%d',  array($lid));
    $row = db_fetch_array($result);
    return (isset($row['nid']) && $row['nid'] ? $row['nid'] : FALSE);
  }
}

// ajax callback to fill infobubble
function getlocations_info() {
  $lid = $_GET['lid'];

  $location = location_load_location($lid);
  $nid = getlocations_get_nid_from_lid($lid);
  $location['nid'] = $nid;
  $content = theme('getlocations_info', $location);

  print $content;
  exit();

}


/**
 * Get the list of marker titles.
 * adapted from gmap
 */
function getlocations_get_marker_titles($reset = FALSE) {
  static $titles;

  if (!$reset) {
    if (is_array($titles)) {
      return $titles;
    }

    $cached = cache_get('getlocations_marker_titles', 'cache');
    if (!empty($cached)) {
      $titles = $cached->data;
      if (is_array($titles)) {
        return $titles;
      }
    }
  }

  module_load_include('inc', 'getlocations', 'getlocations.markerinfo');
  $titles = _getlocations_get_marker_titles();
  cache_set('getlocations_marker_titles', $titles, 'cache');
  return $titles;
}

/**
 * Get the JSON icon data for all the default markers.
 */
function getlocations_get_icondata($reset = FALSE) {
  static $icons;
  if (is_array($icons) && !$reset) {
    return $icons;
  }

  $icons = cache_get('getlocations_icondata');
  if ($icons) {
    $icons = $icons->data;
  }

  if ($reset || !$icons) {
    module_load_include('inc', 'getlocations', 'getlocations.markerinfo');
    $icons = _getlocations_get_icondata();
  }
  cache_set('getlocations_icondata', $icons, 'cache');
  return $icons;
}

/**
 * Regenerate the markerdata file.
 */
function getlocations_regenerate_markers() {
  $contents = '';

  // Create the js/ within the files folder.
  $jspath = file_create_path('js');
  file_check_directory($jspath, FILE_CREATE_DIRECTORY);

  $markerdir = libraries_get_path('getlocations', TRUE) .'/markers';
  $contents .= "// Getlocations marker image data.\n";
  $contents .= "Drupal.getlocations.iconpath = " . drupal_to_js($markerdir) . ";\n";
  $contents .= "Drupal.getlocations.icondata = " . drupal_to_js(getlocations_get_icondata(TRUE)) . ";\n";

  file_save_data($contents, "$jspath/getlocations_markers.js", FILE_EXISTS_REPLACE);

  // Also regenerate the cached marker titles array
  getlocations_get_marker_titles(TRUE);
}

/**
 * Implementation of hook_flush_caches().
 */
function getlocations_flush_caches() {
  getlocations_regenerate_markers();
}

/**
 * Implementation of hook_views_api().
 */
function getlocations_views_api() {
  return array('api' => 2);
}

/**
 * @param int $ct $location $minmaxes
 *
 * @return
 *   Returns $minmaxes
 *
 */
function getlocations_do_minmaxes($ct, $location, $minmaxes) {
  if ($ct) {
    // latitudes
    if ($location['latitude'] > $minmaxes['maxlat']) {
      $minmaxes['maxlat'] = $location['latitude'];
    }
    if ($location['latitude'] < $minmaxes['minlat']) {
      $minmaxes['minlat'] = $location['latitude'];
    }
    // longitudes
    if ($location['longitude'] > $minmaxes['maxlon']) {
      $minmaxes['maxlon'] = $location['longitude'];
    }
    if ($location['longitude'] < $minmaxes['minlon']) {
      $minmaxes['minlon'] = $location['longitude'];
    }
  }
  else {
    $minmaxes['minlat'] = $location['latitude'];
    $minmaxes['maxlat'] = $location['latitude'];
    $minmaxes['minlon'] = $location['longitude'];
    $minmaxes['maxlon'] = $location['longitude'];
  }
  return $minmaxes;
}

// for colorbox and suchlike
function getlocations_box() {

  $a1 = FALSE;
  $a2 = FALSE;
  $a3 = FALSE;
  $a4 = FALSE;

  if (arg(1)) {
    $a1 = arg(1);
  }
  if (arg(2)) {
    $a2 = arg(2);
  }
  if (arg(3)) {
    $a3 = arg(3);
  }
  if (arg(4)) {
    $a4 = arg(4);
  }

  $content = '';

  // $a1 can be node, user, users, type, lids, nids
  if ($a1 == 'node' && $a2) {
    $content .= getlocations_nodemap($a2);
  }
  elseif ($a1 == 'user' && $a2) {
    $content .= getlocations_usermap($a2);
  }
  elseif ($a1 == 'users') {
    $content .= getlocations_usersmap();
  }
  elseif ($a1 == 'type' && $a2) {
    $content .= getlocations_typemap($a2, $a3, $a4);
  }
  elseif ($a1 == 'lids' && $a2) {
    $content .= getlocations_lids($a2);
  }
  elseif ($a1 == 'nids' && $a2) {
    $content .= getlocations_nids($a2);
  }

  $output = theme('getlocations_box', $content);
  print $output;
  exit;
}

