<?php

/**
 * @file
 * @author Bob Hutchinson http://drupal.org/user/52366
 * @copyright GNU GPL
 *
 * Provides Leaflet module integration for Getlocations Fields.
 *
 *
 */

define('GETLOCATIONS_LEAFLET_PATH', drupal_get_path('module', 'getlocations_leaflet'));

/**
 * Implements hook_help().
 */
function getlocations_leaflet_help($path, $arg) {
  switch ($path) {
    case 'admin/help#getlocations':
      $output = '<p>' . t('Provides Leaflet Maps integration for Getlocations.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function getlocations_leaflet_menu() {
  $items = array();
  $items['admin/config/services/getlocations_leaflet'] = array(
    'title' => 'Getlocations leaflet',
    'description' => 'Configure Getlocations leaflet',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('getlocations_leaflet_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  // getlocations/[entity_type]/$nid    # show all location on one entity_type
  $items['getlocations_leaflet/%getlocations_entity_type/%getlocations_id'] = array(
    'title' => 'Get locations',
    'access callback' => 'getlocations_access_location',
    'page callback' => 'getlocations_leaflet_entity_type_map',
    'page arguments' => array(1, 2),
    'type' => MENU_CALLBACK,
  );



  return $items;
}

/**
 * Implements hook_flush_caches().
 */
function getlocations_leaflet_flush_caches() {
  if (variable_get('getlocations_leaflet_flush', 1)) {
    getlocations_leaflet_regenerate_markers();
  }
}

/**
 * Implements hook_library().
 */
function getlocations_leaflet_library() {

  $libraries['leaflet'] = array(
    'title' => 'Leaflet',
    'website' => 'http://leafletjs.com',
    'version' => '0.7',
    'js' => array(
      libraries_get_path('leaflet') . '/leaflet.js' => array(
        'type' => 'file',
        'group' => JS_LIBRARY,
        'preprocess' => FALSE
      ),
    ),
    'css' => array(
      libraries_get_path('leaflet') . '/leaflet.css' => array(
        'type' => 'file',
        'media' => 'all',
      ),
    ),
  );

  $getlocations_leaflet_paths = getlocations_leaflet_paths_get();

  $libraries['getlocations-leaflet'] = array(
    'title' => 'Getlocations Leaflet javascript',
    'website' => 'http://drupal.org/project/getlocations',
    'version' => GETLOCATIONS_VERSION,
    'js' => array(
      $getlocations_leaflet_paths['getlocations_leaflet_path'] => array(
        'type' => 'file',
        'preprocess' => FALSE
      ),
    ),
    'dependencies' => array(
      array('getlocations_leaflet', 'leaflet')
    )
  );

  $libraries['getlocations-leaflet-markercluster'] = array(
    'title' => 'Getlocations Leaflet javascript',
    'website' => 'http://drupal.org/project/getlocations',
    'version' => GETLOCATIONS_VERSION,
    'js' => array(
      GETLOCATIONS_LEAFLET_PATH . '/markercluster/leaflet.markercluster.js' => array(
        'type' => 'file',
        'preprocess' => FALSE
      ),
      $getlocations_leaflet_paths['getlocations_leaflet_path'] => array(
        'type' => 'file',
        'preprocess' => FALSE
      ),
    ),
    'css' => array(
      GETLOCATIONS_LEAFLET_PATH . '/markercluster/MarkerCluster.css' => array(
        'type' => 'file',
        'media' => 'all',
      ),
      GETLOCATIONS_LEAFLET_PATH . '/markercluster/MarkerCluster.Default.css' => array(
        'type' => 'file',
        'media' => 'all',
      ),
      GETLOCATIONS_LEAFLET_PATH . '/markercluster/MarkerCluster.Default.ie.css' => array(
        'browsers' => array(
          'IE' => 'lte IE 8',
          '!IE' => FALSE,
        ),
      ),
    ),
    'dependencies' => array(
      array('getlocations_leaflet', 'leaflet')
    )
  );

  return $libraries;
}



/**
 * Implements hook_views_api().
 */
function getlocations_leaflet_views_api() {
  return array(
    'api' => 3,
    'path' => GETLOCATIONS_LEAFLET_PATH . '/views',
  );
}


/**
 * Implements hook_field_info().
 * Define Field API field types.
 *
 * @return
 *   An array whose keys are field type names and whose values are arrays
 *   describing the field type.
 */
function getlocations_leaflet_field_info() {

  $info = array(
    'getlocations_leaflet' => array(
      'label' => t('Getlocations Leaflet Map'),
      'description' => t('Provide Getlocations Leaflet Map.'),
      'default_formatter' => 'getlocations_leaflet_map',
      'default_widget' => 'getlocations_leaflet_map',
      'settings' => array(),
    )
  );
  return $info;

}

/**
 * Implements hook_field_formatter_info().
 *
 * Declare information about a formatter.
 *
 * @return
 *   An array keyed by formatter name. Each element of the array is an associative
 *   array with these keys and values:
 *   - "label": The human-readable label for the formatter.
 *   - "field types": An array of field type names that can be displayed using
 *     this formatter.
 *
 */
function getlocations_leaflet_field_formatter_info() {

  $formatters = array(
    'getlocations_leaflet_map' => array(
      'label' => t('Getlocations Leaflet Map Field'),
      'field types' => array('getlocations_leaflet'),
      'settings' => getlocations_leaflet_map_formatter_defaults(),
    ),
    'getlocations_leaflet_link' => array(
      'label' => t('Getlocations Leaflet Link Field'),
      'field types' => array('getlocations_leaflet'),
      'settings' => getlocations_leaflet_link_formatter_defaults(),
    ),
  );
  return $formatters;
}

/**
 * Implements hook_field_formatter_view().
 * Build a renderable array for a field value.
 *
 * @param $entity_type
 *   The type of $entity.
 * @param $entity
 *   The entity being displayed.
 * @param $field
 *   The field structure.
 * @param $instance
 *   The field instance.
 * @param $langcode
 *   The language associated with $items.
 * @param $items
 *   Array of values for this field.
 * @param $display
 *   The display settings to use, as found in the 'display' entry of instance definitions.
 * @return
 *   A renderable array for the $items, as an array of child elements keyed
 *   by numeric indexes starting from 0.
 *
 */
function getlocations_leaflet_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  global $language;
  $lang = ($langcode ? $langcode : ($entity->language ? $entity->language : $language->language));
  $settings = $display['settings'];
  $element = array();

  switch ($display['type']) {
    case 'getlocations_leaflet_map':

      if (empty($settings)) {
        $settings = getlocations_leaflet_map_formatter_defaults();
      }

      $module = getlocations_get_current_supported_module();
      $bundle = $instance['bundle'];
      $locative_field_name = (isset($items[0]['locative_field_name']) ? $items[0]['locative_field_name'] : '');
      if ($locative_field_name) {
        $locative_fields = $entity->{$locative_field_name}[$lang];
        $locative_fields_count = count($locative_fields);
        $minmaxes = '';

        // marker
        $marker = '';

        $default_settings = getlocations_leaflet_map_formatter_defaults();
        $default = getlocations_adjust_vars($default_settings, $settings);
        $marker = (isset($default['node_map_marker']) ? $default['node_map_marker'] : '');
        if ($entity_type == 'node') {
          $getlocations_node_marker = variable_get('getlocations_node_marker', array('enable' => 0));
          if ($getlocations_node_marker['enable']) {
            if ($types = getlocations_get_types()) {
              foreach ($types AS $type => $name) {
                if ($type == $bundle) {
                  $field_names = getlocations_get_fieldname2($type, 'node');
                  foreach ($field_names AS $field_name) {
                    if ($field_name == $locative_field_name) {
                      $marker = (isset($getlocations_node_marker['content_type'][$type]['field_name'][$field_name]['map_marker']) ? $getlocations_node_marker['content_type'][$type]['field_name'][$field_name]['map_marker'] : '');
                    }
                  }
                }
              }
            }
          }
        }
        elseif ($entity_type == 'user') {
          $marker = (isset($default['user_map_marker']) ? $default['user_map_marker'] : '');
        }
        elseif ($entity_type == 'taxonomy_term') {
        // TODO needs testing
//////
          if (module_exists('taxonomy')) {
            // vocabulary markers
            if ($types = getlocations_get_vocabularies()) {
              $getlocations_vocabulary_marker = variable_get('getlocations_vocabulary_marker', array('enable' => 0));
              if ($getlocations_vocabulary_marker['enable']) {
                foreach ($types AS $type => $name) {
                  $field_name = getlocations_get_fieldname($type, 'taxonomy_term');

                  if ($field_name == $locative_field_name) {
                    $marker = (isset($getlocations_vocabulary_marker['vocabulary'][$type]['map_marker']) ? $getlocations_vocabulary_marker['vocabulary'][$type]['map_marker'] : $default['vocabulary_map_marker']);
                  }
                }
              }
            }

            // term markers
            $getlocations_term_marker = variable_get('getlocations_term_marker', array('enable' => 0, 'vids' => 0, 'max_depth' => ''));
            if ($getlocations_term_marker['enable'] && $getlocations_term_marker['vids']) {
              $depth = is_numeric($getlocations_term_marker['max_depth']) && $getlocations_term_marker['max_depth'] > 0 ? $getlocations_term_marker['max_depth'] : NULL;
              $vids = $getlocations_term_marker['vids'];
              foreach ($vids AS $vid) {
                $terms = taxonomy_get_tree($vid, 0, $depth);
                foreach ($terms AS $term) {
                  $tid = $term->tid;

                  $marker = (isset($getlocations_term_marker['vid'][$vid]['term'][$tid]['map_marker']) ? $getlocations_term_marker['vid'][$vid]['term'][$tid]['map_marker'] : $default['term_map_marker']);

                }
              }
            }
          }
//////
        }
        elseif ($entity_type == 'comment') {
          $marker = (isset($default['comment_map_marker']) ? $default['comment_map_marker'] : '');
        }

        $mapzoom = FALSE;
        $iconlist = array();
        $minmaxes = array('minlat' => 0, 'minlon' => 0, 'maxlat' => 0, 'maxlon' => 0);

        // fetch lats and lons
        $ct = 0;
        foreach (array_keys($locative_fields) AS $delta) {
          $title = '';
          $lid = 0;
          if (isset($entity->{$locative_field_name}[$lang][$delta]) && $location = $entity->{$locative_field_name}[$lang][$delta]) {
            // collect the lat and lon
            if ($module == 'getlocations_fields') {
              $lat = $location['latitude'];
              $lon = $location['longitude'];
              $lid = (isset($location['glid']) ? $location['glid'] : 0);
            }
            elseif ($module == 'location_cck') {
              $lat = $location['latitude'];
              $lon = $location['longitude'];
              $lid = (isset($location['lid']) ? $location['lid'] : 0);
            }
            elseif ($module == 'geofield') {
              $lat = $location['lat'];
              $lon = $location['lon'];
            }
            elseif ($module == 'geolocation') {
              $lat = $location['lat'];
              $lon = $location['lng'];
            }

            if (isset($lat) && ! empty($lat) && isset($lon) && ! empty($lon)  && $latlon = getlocations_latlon_check($lat . ',' . $lon)) {
              $ll = explode(',', $latlon);
              $location['latitude'] = $ll[0];
              $location['longitude'] = $ll[1];
              $entity_get_info = entity_get_info($entity_type);
              $entity_key = $entity_get_info['entity keys']['id']; // nid, cid, uid etc
              $entity_id = $entity->{$entity_key};

              if (isset($location['name']) && ! empty($location['name'])) {
                $title = $location['name'];
              }
              else {
                $title = (isset($entity->title) ? $entity->title : '');
              }
              $title = htmlspecialchars_decode(strip_tags($title), ENT_QUOTES);
              $minmaxes = getlocations_do_minmaxes($ct, $location, $minmaxes);

              // per item marker
              if (isset($location['marker']) && ! empty($location['marker'])) {
                $marker = $location['marker'];
              }

              if (isset($location['mapzoom'])) {
                $mapzoom = $location['mapzoom'];
              }

              if ($lid && $default['markeraction'] == 'popup') {
                $markeraction = array('type' => 'popup', 'data' => getlocations_getinfo($lid, $entity_key));
              }
              elseif ($lid && $default['markeraction'] == 'link') {
                $markeraction = array('type' => 'link', 'data' => getlocations_getlidinfo($lid, $entity_key));
              }
              else {
                $markeraction = array();
              }

              $iconlist[$marker] = getlocations_leaflet_get_marker($marker);

              $latlons[$ct] = array($location['latitude'], $location['longitude'], $entity_key, $entity_id, $location['glid'], $title, $marker, $markeraction, '');

              $ct++;
            } // end lat lon check
          }
        } // end foreach

        if ($ct < 2 ) {
          unset($minmaxes);
          $minmaxes = '';
        }

        $map_settings = getlocations_leaflet_map_get_info('Getlocations OSM');
        $map_settings = getlocations_leaflet_get_map_layers($map_settings);

        if (! empty($settings['baselayers'])) {
          $map_layers = array();
          foreach ($settings['baselayers'] AS $k => $v) {
            if ($settings['baselayers'][$k]) {
              $map_layers[$k] = $map_settings['map_layers'][$k];
            }
          }
          if (! empty($map_layers)) {
            $map_settings['map_layers'] = $map_layers;
          }
        }

        $nodezoom = FALSE;
        if ($ct == 1 && $settings['nodezoom']) {
          $nodezoom = $settings['nodezoom'];
          $map_settings['map_opts']['center'] = array($location['latitude'], $location['longitude']);
          $map_settings['map_opts']['zoom'] = $nodezoom;
        }
        elseif ($ct < 1) {
          $ll = explode(',', $default['latlong']);
          $map_settings['map_opts']['center'] = array($ll[0], $ll[1]);
        }

        $mapid = getlocations_setup_map('', FALSE, FALSE, TRUE);

        // add in some more
        $map_settings = getlocations_leaflet_map_settings_do($map_settings, $default, $latlons, $mapid);

        $map_settings['map_settings']['nodezoom'] = ($nodezoom ? $nodezoom : FALSE);
        $map_settings['map_settings']['minmaxes'] = (empty($minmaxes) ? FALSE : implode(',', $minmaxes));

        $map_settings['icons'] = $iconlist;
        $map_settings['datanum'] = $ct;
        $map_settings['latlons'] = $latlons;

        if ($map_settings['map_settings']['markercluster']) {
          drupal_add_library('getlocations_leaflet', 'getlocations-leaflet-markercluster');
        }
        else {
          drupal_add_library('getlocations_leaflet', 'getlocations-leaflet');
        }

        getlocations_leaflet_js_settings_do($map_settings, $mapid);
        $element[$delta] = array(
          '#theme' => 'getlocations_leaflet_map',
          '#width' => $default['width'],
          '#height' => $default['height'],
          '#map_settings' => $map_settings,
          '#mapid' => $mapid,
          '#links' => '',
        );

      } // end if ($locative_field_name)
      break;

    case 'getlocations_leaflet_link':

      if (empty($settings) || ! isset($settings['text'])) {
        $settings = getlocations_leaflet_link_formatter_defaults();
      }

      $bundle = $instance['bundle'];
      $locative_field_name = (isset($items[0]['locative_field_name']) ? $items[0]['locative_field_name'] : '');
      if ($locative_field_name) {
        $locative_fields = $entity->{$locative_field_name}[$lang];
        foreach (array_keys($locative_fields) AS $delta) {
          $entity_get_info = entity_get_info($entity_type);
          $entity_key = $entity_get_info['entity keys']['id']; // nid, cid, uid etc
          $entity_id = $entity->{$entity_key};
          $link_text = $settings['text'];
          if ($settings['text_opt'] == 'page') {
            $entity_title = '';
            if (isset($entity_get_info['entity keys']['label'])) {
              $entity_title = $entity_get_info['entity keys']['label'];
            }
            elseif ($entity_type == 'user') {
              $entity_title = 'name';
            }
            if ($entity_title && isset($entity->{$entity_title})) {
              $link_text = $entity->{$entity_title};
            }
          }
          $link_text = check_plain($link_text);
          $element[$delta] = array(
            '#theme' => 'getlocations_leaflet_link',
            '#link_text' => $link_text,
            '#entity_type' => $entity_type,
            '#entity_id' => $entity_id,
          );
        }
      } // end if ($locative_field_name)
      break;
  } // end switch
  return $element;
}


/**
 * Implements hook_field_formatter_settings_summary().
 * Returns a short summary for the current formatter settings of an instance.
 *
 *
 * If an empty result is returned, the formatter is assumed to have no
 * configurable settings, and no UI will be provided to display a settings
 * form.
 *
 *   The field structure.
 * @param $instance
 *   The instance structure.
 * @param $view_mode
 *   The view mode for which a settings summary is requested.
 *
 * @return
 *   A string containing a short summary of the formatter settings.
 */
function getlocations_leaflet_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = array();

  switch ($display['type']) {
    case 'getlocations_leaflet_map':

      $summary[] = t('Getlocations Leaflet Map Field settings');

      if ($settings['zoomControl']) {
        $summary[] = t('Show zoom control: Yes');
      }
      if ($settings['layerControl']) {
        $summary[] = t('Show layer control: Yes');
      }
      if ($settings['scaleControl']) {
        $summary[] = t('Show scale: Yes');
      }

      if ($settings['polygons_enable']) {
        $summary[] = t('Enable polygons: Yes');
        if ($settings['polygons_clickable']) {
          $summary[] = t('Polygons clickable: Yes');
        }
      }
      if ($settings['rectangles_enable']) {
        $summary[] = t('Enable rectangles: Yes');
        if ($settings['rectangles_clickable']) {
          $summary[] = t('Rectangles clickable: Yes');
        }
      }
      if ($settings['circles_enable']) {
        $summary[] = t('Enable circles: Yes');
        if ($settings['circles_clickable']) {
          $summary[] = t('Circles clickable: Yes');
        }
      }
      if ($settings['polylines_enable']) {
        $summary[] = t('Enable polylines: Yes');
        if ($settings['polylines_clickable']) {
          $summary[] = t('Polylines clickable: Yes');
        }
      }


      break;

    case 'getlocations_leaflet_link':
      $summary[] = t('Getlocations Leaflet Link Field settings');
      if ($settings['text_opt']) {
        $summary[] = t('Text options: @a', array('@a' => $settings['text_opt']));
      }
      if ($settings['text']) {
        $summary[] = t('Text: @a', array('@a' => $settings['text']));
      }


      break;

  }
  return implode('<br />', $summary);
}

/**
 * Implements hook_field_formatter_settings_form().
 * Returns form elements for a formatter's settings.
 *
 * @param $field
 *   The field structure being configured.
 * @param $instance
 *   The instance structure being configured.
 * @param $view_mode
 *   The view mode being configured.
 * @param $form
 *   The (entire) configuration form array, which will usually have no use here.
 * @param $form_state
 *   The form state of the (entire) configuration form.
 *
 * @return
 *   The form elements for the formatter settings.
 */
function getlocations_leaflet_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  drupal_add_js(GETLOCATIONS_LEAFLET_PATH . '/js/getlocations_leaflet_formatter.js');

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();
  switch ($display['type']) {
    case 'getlocations_leaflet_map':

      $settings['map_resize'] = 0;
      $settings['fullscreen_disable'] = 0;
      $settings['styles'] = '';
      $labels = array(
        'width' => t('Width'),
        'height' => t('Height'),
      );

      $element += getlocations_map_display_basics_form($settings, $labels);
      unset($element['map_resize']);
      unset($element['fullscreen_disable']);
      unset($element['styles']);
      $element['width']['#element_validate'] = array('getlocations_element_validate_dim');
      $element['height']['#element_validate'] = array('getlocations_element_validate_dim');
      $element['latlong']['#element_validate'] = array('getlocations_element_validate_latlon');

      unset($element['zoom']['#options']['21']);
      unset($element['zoom']['#options']['20']);
      unset($element['zoom']['#options']['19']);

      unset($element['minzoom_map']['#options']['21']);
      unset($element['minzoom_map']['#options']['20']);
      unset($element['minzoom_map']['#options']['19']);

      unset($element['maxzoom_map']['#options']['21']);
      unset($element['maxzoom_map']['#options']['20']);
      unset($element['maxzoom_map']['#options']['19']);

      $element += getlocations_leaflet_display_options_form($settings);

      unset($element['nodezoom']['#options']['21']);
      unset($element['nodezoom']['#options']['20']);
      unset($element['nodezoom']['#options']['19']);

    break;
    case 'getlocations_leaflet_link':
      $element['text'] = array(
        '#type' => 'textfield',
        '#title' => t('Default text'),
        '#description' => t('The text to use if no other option is available.'),
        '#default_value' => $settings['text'],
        '#size' => 25,
      );
      $element['text_opt'] = array(
        '#type' => 'select',
        '#title' => t('Display format'),
        '#default_value' => $settings['text_opt'],
        '#options' => $settings['text_options'],
      );
    break;

  }
  return $element;

}

/**
 * Implements hook_field_widget_info().
 * Expose Field API widget types.
 *
 * @return
 *   An array describing the widget types implemented by the module.
 *
 */
function getlocations_leaflet_field_widget_info() {
  $info = array(
    'getlocations_leaflet_map' => array(
      'label' => t('Getlocations Leaflet Map Field'),
      'field types' => array('getlocations_leaflet'),
      'settings' => array(
        //
      ),
    ),
  );
  return $info;
}

/**
 * Implements hook_field_widget_form().
 * Return the form for a single field widget.
 *
 * @param $form
 *   The form structure where widgets are being attached to. This might be a
 *   full form structure, or a sub-element of a larger form.
 * @param $form_state
 *   An associative array containing the current state of the form.
 * @param $field
 *   The field structure.
 * @param $instance
 *   The field instance.
 * @param $langcode
 *   The language associated with $items.
 * @param $items
 *   Array of default values for this field.
 * @param $delta
 *   The order of this item in the array of subelements (0, 1, 2, etc).
 * @param $element
 *   A form element array containing basic properties for the widget.
 * @return
 *   The form elements for a single widget for this field.
 */
function getlocations_leaflet_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  switch ($instance['widget']['type']) {
    case 'getlocations_leaflet_map':

      // is this real or a demo in settings
      $active = TRUE;
      if (empty($element['#entity'])) {
        $active = FALSE;
      }

      $entity_type = $element['#entity_type'];
      $bundle = $element['#bundle'];
      $module = getlocations_get_current_supported_module();
      #$module = 'getlocations_fields';
      $fieldnames = array();
      $query = db_select('field_config', 'f');
      $query->fields('i', array('field_name', 'data'));
      $query->join('field_config_instance', 'i', 'f.id=i.field_id');
      $query->condition('i.bundle', $bundle)
        ->condition('f.module', $module)
        ->condition('i.entity_type', $entity_type)
        ->condition('f.active', 1);
      $rows = $query->execute();
      foreach ($rows AS $row) {
        $data = unserialize($row->data);
        $fieldnames[$row->field_name] = $data['label'];
      }

      $cardinality = $field['cardinality'];
      // Wrap in a fieldset for single fields
      if ($cardinality == 1) {
        $element['#type'] = 'fieldset';
        $element['#collapsible'] = TRUE;
        $element['#collapsed'] = FALSE;
      }

      if (! empty($fieldnames)) {
        $element['#delta'] = $delta;
        $dval = (isset($items[$delta]['locative_field_name']) ? $items[$delta]['locative_field_name'] : (isset($instance['default_value'][$delta]['locative_field_name']) ? $instance['default_value'][$delta]['locative_field_name'] : ''));
        // items only see which field, no choice
        if ($active && $dval) {
          $element['locative_field_name'] = array('#type' => 'value', '#value' => $dval);
          $element['locative_field_name_markup'] = array('#markup' => '<p>' . t('Locative data taken from !f', array('!f' => $fieldnames[$dval])) . '</p>');
         }
        else {
          $element['locative_field_name'] = array(
            '#type' => 'select',
            '#title' => t('Location Field'),
            '#options' => $fieldnames,
            '#description' => t('Field to take locative data from'),
            '#default_value' => $dval,
          );
        }
      }
      else {
        if (! $active) {
          $element['some_info'] = array(
            '#type' => 'markup',
            '#markup' => '<p>' . t('You must attach an instance of !m', array('!m' => $module))
          );
        }
      }

      break;
  }
  return $element;

}

/**
 * Implements hook_field_widget_error().
 *
 * hook_field_widget_error() lets us figure out what to do with errors
 * we might have generated in hook_field_validate(). Generally, we'll just
 * call form_error().
 *
 */
function getlocations_leaflet_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'getlocations_leaflet_field_invalid':
      form_error($element, $error['message']);
      break;
  }

}


/**
 * Implements hook_field_is_empty().
 * Define what constitutes an empty item for a field type.
 * hook_field_is_emtpy() is where Drupal asks us if this field is empty.
 * Return TRUE if it does not contain data, FALSE if it does. This lets
 * the form API flag an error when required fields are empty.
 *
 * @param $item
 *   An item that may or may not be empty.
 * @param $field
 *   The field to which $item belongs.
 * @return
 *   TRUE if $field's type considers $item not to contain any data;
 *   FALSE otherwise.
 */
function getlocations_leaflet_field_is_empty($item, $field) {
  return FALSE;
}


function getlocations_leaflet_map_formatter_defaults() {
  return getlocations_leaflet_defaults();
}


function getlocations_leaflet_link_formatter_defaults() {
  return array(
    'text' => t('this location'),
    'text_opt' => 'page',
    'text_options' => array(
      '' => t('None'),
      'page' => t('Page title'),
    ),
  );
}

function getlocations_leaflet_map_settings_do($map_settings, $defaults, $latlons, $mapid) {

  $map_settings['map_opts']['dragging']           = ($defaults['dragging'] ? TRUE : FALSE);
  $map_settings['map_opts']['scrollWheelZoom']    = ($defaults['scrollWheelZoom'] ? TRUE : FALSE);
  $map_settings['map_opts']['doubleClickZoom']    = ($defaults['doubleClickZoom'] ? TRUE : FALSE);
  $map_settings['map_opts']['touchZoom']          = ($defaults['touchZoom'] ? TRUE : FALSE);
  $map_settings['map_opts']['trackResize']        = ($defaults['trackResize'] ? TRUE : FALSE);
  $map_settings['map_opts']['fadeAnimation']      = ($defaults['fadeAnimation'] ? TRUE : FALSE);
  $map_settings['map_opts']['zoomAnimation']      = ($defaults['zoomAnimation'] ? TRUE : FALSE);
  $map_settings['map_opts']['closePopupOnClick']  = ($defaults['closePopupOnClick'] ? TRUE : FALSE);

  $map_settings['map_settings']['markercluster']  = ($defaults['markercluster'] ? TRUE : FALSE);
  $map_settings['map_settings']['markerclusteroptions'] = '';
  if (file_exists(GETLOCATIONS_LEAFLET_PATH . '/markercluster/markerclusteroptions.inc')) {
    module_load_include('inc', 'getlocations_leaflet', 'markercluster/markerclusteroptions');
    if (function_exists('getlocations_leaflet_get_markerclusteroptions')) {
      $map_settings['map_settings']['markerclusteroptions'] = getlocations_leaflet_get_markerclusteroptions();
    }
  }

  // Zoom
  if ($defaults['zoomControl'] && $defaults['zoomcontrolposition']) {
    $map_settings['map_opts']['zoomControl'] = FALSE;
    $map_settings['map_settings']['zoomControl'] = TRUE;
    $map_settings['map_settings']['zoomcontrolposition'] = $defaults['zoomcontrolposition'];
  }
  else {
    $map_settings['map_opts']['zoomControl'] = ($defaults['zoomControl'] ? TRUE : FALSE);
    $map_settings['map_settings']['zoomControl'] = FALSE;
    $map_settings['map_settings']['zoomcontrolposition'] = '';
  }
  // Attribution
  if ($defaults['attributionControl'] && $defaults['attributioncontrolposition']) {
    $map_settings['map_opts']['attributionControl'] = FALSE;
    $map_settings['map_settings']['attributionControl'] = TRUE;
    $map_settings['map_settings']['attributioncontrolposition'] = $defaults['attributioncontrolposition'];
  }
  else {
    $map_settings['map_opts']['attributionControl'] = ($defaults['attributionControl'] ? TRUE : FALSE);
    $map_settings['map_settings']['attributionControl'] = FALSE;
    $map_settings['map_settings']['attributioncontrolposition'] = '';
  }
  // Layer
  if ($defaults['layerControl'] && $defaults['layercontrolposition']) {
    $map_settings['map_opts']['layerControl'] = FALSE;
    $map_settings['map_settings']['layerControl'] = TRUE;
    $map_settings['map_settings']['layercontrolposition'] = $defaults['layercontrolposition'];
  }
  else {
    $map_settings['map_opts']['layerControl'] = FALSE;
    $map_settings['map_settings']['layerControl'] = ($defaults['layerControl'] ? TRUE : FALSE);
    $map_settings['map_settings']['layercontrolposition'] = '';
  }
  // overlays
  $map_settings['map_settings']['layercontrol_mark_ov'] = ($defaults['layercontrol_mark_ov'] ? TRUE : FALSE);
  $map_settings['map_settings']['layercontrol_mark_ov_label'] = $defaults['layercontrol_mark_ov_label'];

  $map_settings['map_settings']['layercontrol_circ_ov'] = ($defaults['layercontrol_circ_ov'] ? TRUE : FALSE);
  $map_settings['map_settings']['layercontrol_circ_ov_label'] = $defaults['layercontrol_circ_ov_label'];

  $map_settings['map_settings']['layercontrol_polyl_ov'] = ($defaults['layercontrol_polyl_ov'] ? TRUE : FALSE);
  $map_settings['map_settings']['layercontrol_polyl_ov_label'] = $defaults['layercontrol_polyl_ov_label'];

  $map_settings['map_settings']['layercontrol_polyg_ov'] = ($defaults['layercontrol_polyg_ov'] ? TRUE : FALSE);
  $map_settings['map_settings']['layercontrol_polyg_ov_label'] = $defaults['layercontrol_polyg_ov_label'];

  $map_settings['map_settings']['layercontrol_rect_ov'] = ($defaults['layercontrol_rect_ov'] ? TRUE : FALSE);
  $map_settings['map_settings']['layercontrol_rect_ov_label'] = $defaults['layercontrol_rect_ov_label'];

  // Scale
  $map_settings['map_settings']['scaleControl'] = ($defaults['scaleControl'] ? TRUE : FALSE);
  $map_settings['map_settings']['scalecontrolposition'] = $defaults['scalecontrolposition'];
  $map_settings['map_settings']['scalecontrolunits'] = $defaults['scalecontrolunits'];

  if ($defaults['minzoom_map'] > -1) {
    $map_settings['map_opts']['minZoom'] = $defaults['minzoom_map'];
  }
  if ($defaults['maxzoom_map'] > -1) {
    $map_settings['map_opts']['maxZoom'] = $defaults['maxzoom_map'];
  }

  $getlocations_leaflet_paths = getlocations_leaflet_paths_get();
  // shapes
  // polygons
  if ($defaults['polygons_enable'] && ! empty($defaults['polygons_coords'])) {
    $polygons = getlocations_get_polygon_settings($defaults);
    if ($polygons) {
      $polygon_settings = array(
        $mapid => $polygons,
      );
      drupal_add_js(array('getlocations_leaflet_polygons' => $polygon_settings), 'setting');
      drupal_add_js($getlocations_leaflet_paths['getlocations_leaflet_polygons_path']);
}
  }

  // rectangles
  if ($defaults['rectangles_enable'] && (! empty($defaults['rectangles_coords']) || ($defaults['rectangles_apply'] && $defaults['rectangles_dist']))) {
    if ($defaults['rectangles_apply'] && $defaults['rectangles_dist']) {
      // get latlons and set coords
      $tmp = '';
      foreach ($latlons AS $ll) {
        $lats = getlocations_earth_latitude_range($ll[0], $ll[1], $defaults['rectangles_dist']);
        $lngs = getlocations_earth_longitude_range($ll[0], $ll[1], $defaults['rectangles_dist']);
        $tmp .= $lats[0] . ',' . $lngs[0] . '|' . $lats[1] . ',' . $lngs[1] . "\n";
      }
      if ($tmp) {
        $defaults['rectangles_coords'] = $tmp;
      }
    }
    $rectangles = getlocations_get_rectangle_settings($defaults);
    if ($rectangles) {
      $rectangle_settings = array(
        $mapid => $rectangles,
      );
      drupal_add_js(array('getlocations_leaflet_rectangles' => $rectangle_settings), 'setting');
      drupal_add_js($getlocations_leaflet_paths['getlocations_leaflet_rectangles_path']);
    }
  }

  // circles
  if ($defaults['circles_enable'] && $defaults['circles_radius'] > 0 && (! empty($defaults['circles_coords']) || $defaults['circles_apply'])) {
    if ($defaults['circles_apply'] && count($latlons)) {
      // get latlons and set coords
      $tmp = '';
      foreach ($latlons AS $ll) {
        $tmp .= $ll[0] . ',' . $ll[1] . "\n";
      }
      if ($tmp) {
        $defaults['circles_coords'] = $tmp;
      }
    }
    $circles = getlocations_get_circle_settings($defaults);
    if ($circles) {
      $circle_settings = array(
        $mapid => $circles,
      );
      drupal_add_js(array('getlocations_leaflet_circles' => $circle_settings), 'setting');
      drupal_add_js($getlocations_leaflet_paths['getlocations_leaflet_circles_path']);
    }
  }

  // polylines
  if ($defaults['polylines_enable'] && ! empty($defaults['polylines_coords'])) {
    $polylines = getlocations_get_polyline_settings($defaults);
    if ($polylines) {
      $polyline_settings = array(
        $mapid => $polylines,
      );
      drupal_add_js(array('getlocations_leaflet_polylines' => $polyline_settings), 'setting');
      drupal_add_js($getlocations_leaflet_paths['getlocations_leaflet_polylines_path']);
    }
  }

  // geojson
  if ($defaults['geojson_enable'] && !empty($defaults['geojson_data']) && $geojson_path = getlocations_get_geojson_path() ) {
    drupal_add_js($geojson_path);
    $geojson_settings = array(
      $mapid => array(
        'geojson_data' => $defaults['geojson_data'],
        'geojson_options' => $defaults['geojson_options'],
      )
    );
    drupal_add_js(array('getlocations_leaflet_geojson' => $geojson_settings), 'setting');
    drupal_add_js($getlocations_leaflet_paths['getlocations_leaflet_geojson_path']);
  }

  return $map_settings;
}


function getlocations_leaflet_js_settings_do($defaults, $mapid) {

  $settings = array(
    $mapid => $defaults
  );
  drupal_add_js(array('getlocations_leaflet' => $settings), 'setting');

}

function getlocations_leaflet_get_icondata($reset = FALSE) {

  static $icons;
  if (is_array($icons) && !$reset) {
    return $icons;
  }

  $icons = cache_get('getlocations_leaflet_icondata');
  if ($icons) {
    $icons = $icons->data;
  }

  if ($reset || !$icons) {
    module_load_include('inc', 'getlocations_leaflet', 'getlocations_leaflet.markerinfo');
    $icons = _getlocations_leaflet_get_icondata();
  }
  if ($icons) {
    cache_set('getlocations_leaflet_icondata', $icons, 'cache');
  }
  return $icons;

}

function getlocations_leaflet_regenerate_markers() {
  $icons = getlocations_leaflet_get_icondata(TRUE);
  if (! $icons) {
    // no markers found
    drupal_set_message(t('No markers found, you need to install some markers, please see the project page for details.'), 'error');
    watchdog('getlocations_leaflet', 'No markers found.', array(), WATCHDOG_ERROR);
    return FALSE;
  }
  return TRUE;
}

function getlocations_leaflet_get_marker($key) {
  $icons = getlocations_leaflet_get_icondata();
  if (isset($icons[$key])) {
    return $icons[$key];
  }
  return FALSE;
}

function getlocations_leaflet_marker_list() {
  $icons = getlocations_leaflet_get_icondata();
  if (! $icons) {
    // no markers found
    drupal_set_message(t('No markers found, you need to install some markers, please see the project page for details.'), 'error');
    watchdog('getlocations_leaflet', 'No markers found.', array(), WATCHDOG_ERROR);
    return FALSE;
  }
  $data = array();
  foreach ($icons AS $k => $v) {
    $data[$k] = $v['name'];
  }
}

function getlocations_leaflet_controlpositions($dd = TRUE) {
  if ($dd) {
    $controlpositions = array(
      ''   => t('Default'),
      'topleft' => t('Top Left'),
      'topright' => t('Top Right'),
      'bottomright' => t('Bottom Right'),
      'bottomleft' => t('Bottom Left'),
    );
  }
  else {
    $controlpositions = array('topleft', 'topright', 'bottomright', 'bottomleft');
  }
  return $controlpositions;
}

/**
 * Get all available Leaflet map definitions.
 *
 * Derived from the leaflet module
 *
 * @param string $map
 */
function getlocations_leaflet_map_get_info($map = NULL) {
  static $drupal_static_fast;
  if (!isset($drupal_static_fast)) {
    $drupal_static_fast['getlocations_leaflet_map_info'] = &drupal_static(__FUNCTION__);
  }
  $map_info = &$drupal_static_fast['getlocations_leaflet_map_info'];

  if (empty($map_info)) {
    if ($cache = cache_get("getlocations_leaflet_map_info")) {
      $map_info = $cache->data;
    }
    else {
      $map_info = module_invoke_all('getlocations_leaflet_map_info');

      // Let other modules alter the map info.
      drupal_alter('getlocations_leaflet_map_info', $map_info);

      cache_set("getlocations_leaflet_map_info", $map_info);
    }
  }

  if (empty($map)) {
    return $map_info;
  }
  elseif (isset($map_info[$map])) {
    return $map_info[$map];
  }
}

/**
 * Implements hook_getlocations_leaflet_map_info().
 *
 */
function getlocations_leaflet_getlocations_leaflet_map_info() {
  $name = 'OSM map';
  $urlTemplate = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
  $attribution = 'OSM map data @ <a target="_blank" href="http://www.openstreetmap.org/">OpenStreetMap contributors</a>, <a target="_blank" href="http://www.openstreetmap.org/copyright">ODBL</a>';
  return array(
    'Getlocations OSM' => array(
      'label' => 'Getlocations OSM',
      'description' => t('Getlocations Leaflet maps.'),
      'map_opts' => array(
        'dragging'                   => TRUE,
        'touchZoom'                  => TRUE,
        'scrollWheelZoom'            => TRUE,
        'doubleClickZoom'            => TRUE,
        'zoomControl'                => TRUE,
        'attributionControl'         => TRUE,
        'trackResize'                => TRUE,
        'fadeAnimation'              => TRUE,
        'zoomAnimation'              => TRUE,
        'closePopupOnClick'          => TRUE,
        'layerControl'               => TRUE,
        'minZoom'                    => 0,
        'maxZoom'                    => 18,
      ),
      'map_settings' => array(
        'zoomcontrolposition'        => '',
        'attributioncontrolposition' => '',
        'layercontrolposition'       => '',
        'scaleControl'               => FALSE,
        'scalecontrolposition'       => '',
        'scalecontrolunits'          => '',
        'markeraction'               => '',
      ),
      'map_layers' => array(
        "$name" => array(
          'urlTemplate' => $urlTemplate,
          'options' => array(
            'attribution' => $attribution
          ),
          'description' => t('OpenStreet Map'),
        ),
      ),
    ),
  );
}

function getlocations_leaflet_defaults() {
  $getlocations_defaults = getlocations_defaults();
  $defaults = array(
    'width'                      => $getlocations_defaults['width'],
    'height'                     => $getlocations_defaults['height'],
    'zoom'                       => $getlocations_defaults['zoom'],
    'minzoom_map'                => $getlocations_defaults['minzoom_map'],
    'maxzoom_map'                => $getlocations_defaults['maxzoom_map'],
    'latlong'                    => $getlocations_defaults['latlong'],
    'nodezoom'                   => $getlocations_defaults['nodezoom'],
    'polygons_enable'            => $getlocations_defaults['polygons_enable'],
    'polygons_strokecolor'       => $getlocations_defaults['polygons_strokecolor'],
    'polygons_strokeopacity'     => $getlocations_defaults['polygons_strokeopacity'],
    'polygons_strokeweight'      => $getlocations_defaults['polygons_strokeweight'],
    'polygons_fillcolor'         => $getlocations_defaults['polygons_fillcolor'],
    'polygons_fillopacity'       => $getlocations_defaults['polygons_fillopacity'],
    'polygons_coords'            => $getlocations_defaults['polygons_coords'],
    'polygons_clickable'         => $getlocations_defaults['polygons_clickable'],
    'polygons_message'           => $getlocations_defaults['polygons_message'],
    'rectangles_enable'          => $getlocations_defaults['rectangles_enable'],
    'rectangles_strokecolor'     => $getlocations_defaults['rectangles_strokecolor'],
    'rectangles_strokeopacity'   => $getlocations_defaults['rectangles_strokeopacity'],
    'rectangles_strokeweight'    => $getlocations_defaults['rectangles_strokeweight'],
    'rectangles_fillcolor'       => $getlocations_defaults['rectangles_fillcolor'],
    'rectangles_fillopacity'     => $getlocations_defaults['rectangles_fillopacity'],
    'rectangles_coords'          => $getlocations_defaults['rectangles_coords'],
    'rectangles_clickable'       => $getlocations_defaults['rectangles_clickable'],
    'rectangles_message'         => $getlocations_defaults['rectangles_message'],
    'rectangles_apply'           => $getlocations_defaults['rectangles_apply'],
    'rectangles_dist'            => $getlocations_defaults['rectangles_dist'],
    'circles_enable'             => $getlocations_defaults['circles_enable'],
    'circles_strokecolor'        => $getlocations_defaults['circles_strokecolor'],
    'circles_strokeopacity'      => $getlocations_defaults['circles_strokeopacity'],
    'circles_strokeweight'       => $getlocations_defaults['circles_strokeweight'],
    'circles_fillcolor'          => $getlocations_defaults['circles_fillcolor'],
    'circles_fillopacity'        => $getlocations_defaults['circles_fillopacity'],
    'circles_coords'             => $getlocations_defaults['circles_coords'],
    'circles_clickable'          => $getlocations_defaults['circles_clickable'],
    'circles_message'            => $getlocations_defaults['circles_message'],
    'circles_radius'             => $getlocations_defaults['circles_radius'],
    'circles_apply'              => $getlocations_defaults['circles_apply'],
    'polylines_enable'           => $getlocations_defaults['polylines_enable'],
    'polylines_strokecolor'      => $getlocations_defaults['polylines_strokecolor'],
    'polylines_strokeopacity'    => $getlocations_defaults['polylines_strokeopacity'],
    'polylines_strokeweight'     => $getlocations_defaults['polylines_strokeweight'],
    'polylines_coords'           => $getlocations_defaults['polylines_coords'],
    'polylines_clickable'        => $getlocations_defaults['polylines_clickable'],
    'polylines_message'          => $getlocations_defaults['polylines_message'],
    // categories
    'category_method'            => $getlocations_defaults['category_method'],
    'category_term_reference_field' => $getlocations_defaults['category_term_reference_field'],
    'category_showhide_buttons'  => $getlocations_defaults['category_showhide_buttons'],
    'categories'                 => $getlocations_defaults['categories'],
    'returnlink_page_enable'     => $getlocations_defaults['returnlink_page_enable'],
    'returnlink_page_link'       => $getlocations_defaults['returnlink_page_link'],
    'returnlink_user_enable'     => $getlocations_defaults['returnlink_user_enable'],
    'returnlink_user_link'       => $getlocations_defaults['returnlink_user_link'],
    'returnlink_term_enable'     => $getlocations_defaults['returnlink_term_enable'],
    'returnlink_term_link'       => $getlocations_defaults['returnlink_term_link'],
    'returnlink_comment_enable'  => $getlocations_defaults['returnlink_comment_enable'],
    'returnlink_comment_link'    => $getlocations_defaults['returnlink_comment_link'],
    'geojson_enable'             => $getlocations_defaults['geojson_enable'],
    'geojson_data'               => $getlocations_defaults['geojson_data'],
    'geojson_options'            => $getlocations_defaults['geojson_options'],

  );

  $newdefaults = getlocations_adjust_vars($getlocations_defaults, $defaults);
  $newdefaults['dragging']           = $getlocations_defaults['draggable'];
  $newdefaults['scrollWheelZoom']    = $getlocations_defaults['scrollwheel'];
  $newdefaults['doubleClickZoom']    = ($getlocations_defaults['nodoubleclickzoom'] ? 0 : 1);
  $newdefaults['zoomControl']        = ($getlocations_defaults['controltype'] == 'none' ? 0 : 1);
  $newdefaults['touchZoom']          = 1;
  $newdefaults['attributionControl'] = 1;
  $newdefaults['trackResize']        = 1;
  $newdefaults['fadeAnimation']      = 1;
  $newdefaults['zoomAnimation']      = 1;
  $newdefaults['closePopupOnClick']  = 1;
  $newdefaults['layerControl']       = 0;

  $newdefaults['scaleControl']       = $getlocations_defaults['scale'];
  $newdefaults['scalecontrolposition']       = '';
  $newdefaults['scalecontrolunits']          = '';
  $newdefaults['zoomcontrolposition']        = '';
  $newdefaults['attributioncontrolposition'] = '';
  $newdefaults['layercontrolposition']       = '';
  $newdefaults['layercontrol_mark_ov']       = 9;
  $newdefaults['layercontrol_mark_ov_label'] = t('Locations');

  $newdefaults['layercontrol_circ_ov']       = 9;
  $newdefaults['layercontrol_circ_ov_label'] = t('Circles');

  $newdefaults['layercontrol_polyl_ov']       = 9;
  $newdefaults['layercontrol_polyl_ov_label'] = t('Lines');

  $newdefaults['layercontrol_polyg_ov']       = 9;
  $newdefaults['layercontrol_polyg_ov_label'] = t('Polygons');

  $newdefaults['layercontrol_rect_ov']       = 9;
  $newdefaults['layercontrol_rect_ov_label'] = t('Rectangles');

  $newdefaults['markeraction']               = '';
  $newdefaults['markercluster']              = 0;
  $newdefaults['baselayers']              = array();

  $settings = variable_get('getlocations_leaflet_defaults', '');
  $settings = getlocations_adjust_vars($newdefaults, $settings);
  return $settings;
}

function getlocations_leaflet_get_map_layers($map_settings) {
  $map_layers = $map_settings['map_layers'];
  $cloudmade_info = variable_get('getlocations_leaflet_cloudmade', '');
  if (! empty($cloudmade_info)) {
    if (isset($cloudmade_info['cloudmade_key']) && ! empty($cloudmade_info['cloudmade_key'])) {
      $cloudmade_key = $cloudmade_info['cloudmade_key'];
      if (isset($cloudmade_info['cloudmade_maps']) && is_array($cloudmade_info['cloudmade_maps']) ) {
        $add = array();
        foreach ($cloudmade_info['cloudmade_maps'] AS $k => $map) {
          $style_id = $map['style_id'];
          $style_name = $map['style_name'];
          $style_description = $map['style_description'];
          $style_token = $map['style_token'];
          $query = '';
          if (! empty($style_token)) {
            $query = '?token=' . $style_token;
          }
          $mobile = '';
          $size = '256';
          if (getlocations_is_mobile()) {
            $mobile = '@2x';
            $size = '64';
          }
          $urlTemplate = 'http://{s}.tile.cloudmade.com/' . $cloudmade_key . '/' . $style_id . $mobile . '/' . $size . '/{z}/{x}/{y}.png' . $query;
          $attribution = '© <a target="_blank" href="http://cloudmade.com">Cloudmade ' . $style_id . '</a>';
          $add[$style_name] = array(
            'urlTemplate' => $urlTemplate,
            'options' => array('attribution' => $attribution),
            'description' => $style_description
          );
        }
        if (count($add)) {
          $map_layers += $add;
        }
      }
    }
  }

  // make sure default is last
  $default_map_info = getlocations_leaflet_getlocations_leaflet_map_info();
  $default_map_layer = $default_map_info['Getlocations OSM']['map_layers'];
  unset($map_layers['OSM map']);
  $map_layers += $default_map_layer;

  $map_settings['map_layers'] = $map_layers;
  return $map_settings;
}

function getlocations_leaflet_display_options_form($defaults) {
  $form = array();

  $controlpositions = getlocations_leaflet_controlpositions();

  $form['nodezoom'] = getlocations_element_map_zoom(
    t('Default Zoom for Single location'),
    $defaults['nodezoom'],
    t('The Default zoom level for a single marker.')
  );

  $form['scrollWheelZoom'] = getlocations_element_map_checkbox(
    t('Scrollwheel'),
    $defaults['scrollWheelZoom'],
    t('Enable scrollwheel zooming.')
  );
  $form['touchZoom'] = getlocations_element_map_checkbox(
    t('Touch Zoom'),
    $defaults['touchZoom'],
    t('Enable touch zooming. Applies to touchscreens.')
  );

  $form['dragging'] = getlocations_element_map_checkbox(
    t('Draggable'),
    $defaults['dragging'],
    t('Enable dragging the map.')
  );

  $form['doubleClickZoom'] = getlocations_element_map_checkbox(
    t('DoubleClick Zoom'),
    $defaults['doubleClickZoom'],
    t('Enable DoubleClick Zooming.')
  );

  $form['scaleControl'] = getlocations_element_map_checkbox(
    t('Scale'),
    $defaults['scaleControl'],
    t('Show scale.')
  );
  $form['scaleControl']['#suffix'] = '<div id="wrap-getlocations-scalecontrol">';
  $form['scalecontrolunits'] = getlocations_element_dd(
    t('Distance Units'),
    $defaults['scalecontrolunits'],
    array('' => t('Defaults'), 'metric' => t('Metric'), 'imperial' => t('Imperial'))
  );
  $form['scalecontrolposition'] = getlocations_element_dd(
    t('Position of Scale Control'),
    $defaults['scalecontrolposition'],
    $controlpositions
  );
  $form['scalecontrolposition']['#suffix'] = '</div>';

  $form['zoomControl'] = getlocations_element_map_checkbox(
    t('Zoom Control'),
    $defaults['zoomControl'],
    t('Enable Zoom Control on the map.')
  );
  $form['zoomControl']['#suffix'] = '<div id="wrap-getlocations-zoomcontrol">';
  $form['zoomcontrolposition'] = getlocations_element_dd(
    t('Position of Zoom Control'),
    $defaults['zoomcontrolposition'],
    $controlpositions
  );
  $form['zoomcontrolposition']['#suffix'] = '</div>';

  $form['attributionControl'] = getlocations_element_map_checkbox(
    t('Attribution Control'),
    $defaults['attributionControl'],
    t('Enable Attribution Control on the map.')
  );
  $form['attributionControl']['#suffix'] = '<div id="wrap-getlocations-attributioncontrol">';
  $form['attributioncontrolposition'] = getlocations_element_dd(
    t('Position of Attribution Control'),
    $defaults['attributioncontrolposition'],
    $controlpositions
  );
  $form['attributioncontrolposition']['#suffix'] = '</div>';

  $form['layerControl'] = getlocations_element_map_checkbox(
    t('Layer Control'),
    $defaults['layerControl'],
    t('Enable Layer Control on the map.')
  );
  $form['layerControl']['#suffix'] = '<div id="wrap-getlocations-layercontrol">';

  $form['layercontrol_mark_ov'] = getlocations_element_map_checkbox(
    t('Layer Control Marker Overlay'),
    $defaults['layercontrol_mark_ov'],
    t('Add a checkbox to switch Markers on and off to the Layer Control.')
  );
  $form['layercontrol_mark_ov_label'] = getlocations_element_map_tf(
    t('Layer Control Marker Overlay Label'),
    $defaults['layercontrol_mark_ov_label'],
    t('The label to display on the Layer Control.'),
    20
  );

  $form['layercontrol_circ_ov'] = getlocations_element_map_checkbox(
    t('Layer Control Circles Overlay'),
    $defaults['layercontrol_circ_ov'],
    t('Add a checkbox to switch Circles on and off to the Layer Control.')
  );
  $form['layercontrol_circ_ov_label'] = getlocations_element_map_tf(
    t('Layer Control Circles Overlay Label'),
    $defaults['layercontrol_circ_ov_label'],
    t('The label to display on the Layer Control.'),
    20
  );

  $form['layercontrol_polyl_ov'] = getlocations_element_map_checkbox(
    t('Layer Control Lines Overlay'),
    $defaults['layercontrol_polyl_ov'],
    t('Add a checkbox to switch Lines on and off to the Layer Control.')
  );
  $form['layercontrol_polyl_ov_label'] = getlocations_element_map_tf(
    t('Layer Control Lines Overlay Label'),
    $defaults['layercontrol_polyl_ov_label'],
    t('The label to display on the Layer Control.'),
    20
  );

  $form['layercontrol_polyg_ov'] = getlocations_element_map_checkbox(
    t('Layer Control Polygons Overlay'),
    $defaults['layercontrol_polyg_ov'],
    t('Add a checkbox to switch Polygons on and off to the Layer Control.')
  );
  $form['layercontrol_polyg_ov_label'] = getlocations_element_map_tf(
    t('Layer Control Polygons Overlay Label'),
    $defaults['layercontrol_polyg_ov_label'],
    t('The label to display on the Layer Control.'),
    20
  );

  $form['layercontrol_rect_ov'] = getlocations_element_map_checkbox(
    t('Layer Control Rectangles Overlay'),
    $defaults['layercontrol_rect_ov'],
    t('Add a checkbox to switch Rectangles on and off to the Layer Control.')
  );
  $form['layercontrol_rect_ov_label'] = getlocations_element_map_tf(
    t('Layer Control Rectangles Overlay Label'),
    $defaults['layercontrol_rect_ov_label'],
    t('The label to display on the Layer Control.'),
    20
  );

  $form['layercontrolposition'] = getlocations_element_dd(
    t('Position of Layer Control'),
    $defaults['layercontrolposition'],
    $controlpositions
  );
  $form['layercontrolposition']['#suffix'] = '</div>';

  // baselayers
  $map_settings = getlocations_leaflet_map_get_info('Getlocations OSM');
  $map_settings = getlocations_leaflet_get_map_layers($map_settings);
  $map_layers = $map_settings['map_layers'];
  // reconfigure $defaults['baselayers']
  $old_baselayers = $defaults['baselayers'];
  $defaults['baselayers'] = array();
  foreach ($map_layers AS $k => $v) {
    if ($k == 'OSM map') {
      $defaults['baselayers'][$k] = (isset($old_baselayers[$k]) ? $old_baselayers[$k] : 1);
    }
    else {
      $defaults['baselayers'][$k] = (isset($old_baselayers[$k]) ? $old_baselayers[$k] : 0);
    }
  }
  $form['baselayers'] =  array(
    '#type' => 'fieldset',
    '#title' => t('Enable map types'),
    '#description' => t('Select which maps you want to be available. You must select at least one'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  foreach ($defaults['baselayers'] AS $key => $value) {
    $form['baselayers'][$key] = getlocations_element_map_checkbox(
      $key,
      $defaults['baselayers'][$key],
      (isset($map_layers[$key]['description']) ? $map_layers[$key]['description'] : '')
    );
  }

  $form['trackResize'] = getlocations_element_map_checkbox(
    t('Automatic Resizing'),
    $defaults['trackResize'],
    t('Enable Automatic Resizing of the map.')
  );

  $form['fadeAnimation'] = getlocations_element_map_checkbox(
    t('fadeAnimation'),
    $defaults['fadeAnimation'],
    t('Enable fadeAnimation on the map.')
  );

  $form['zoomAnimation'] = getlocations_element_map_checkbox(
    t('zoomAnimation'),
    $defaults['zoomAnimation'],
    t('Enable zoomAnimation on the map.')
  );

  $form['closePopupOnClick'] = getlocations_element_map_checkbox(
    t('closePopupOnClick'),
    $defaults['closePopupOnClick'],
    t('Enable closePopupOnClick on the map.')
  );

  $form['markeraction'] = getlocations_element_dd(
    t('Marker action'),
    $defaults['markeraction'],
    array(
      '' => t('None'),
      'popup' => t('Popup'),
      'link' => t('Link to content')
    )
  );
  $form['markercluster'] = getlocations_element_map_checkbox(
    t('Marker Cluster'),
    $defaults['markercluster'],
    t('Enable markercluster on the map.')
  );

  // shapes
  $form += getlocations_shapes_form($defaults, '');

  // geojson
  $form += getlocations_geojson_form($defaults);
  $form['geojson_options']['#type'] = 'hidden';

  return $form;
}



function getlocations_leaflet_paths_get($reset = FALSE) {

  $defaults = array(
    'getlocations_leaflet_path'            => GETLOCATIONS_LEAFLET_PATH . '/js/getlocations_leaflet.js',
    'getlocations_leaflet_circles_path'    => GETLOCATIONS_LEAFLET_PATH . '/js/getlocations_leaflet_circles.js',
    'getlocations_leaflet_formatter_path'  => GETLOCATIONS_LEAFLET_PATH . '/js/getlocations_leaflet_formatter.js',
    'getlocations_leaflet_polygons_path'   => GETLOCATIONS_LEAFLET_PATH . '/js/getlocations_leaflet_polygons.js',
    'getlocations_leaflet_polylines_path'  => GETLOCATIONS_LEAFLET_PATH . '/js/getlocations_leaflet_polylines.js',
    'getlocations_leaflet_rectangles_path' => GETLOCATIONS_LEAFLET_PATH . '/js/getlocations_leaflet_rectangles.js',
    'getlocations_leaflet_geojson_path'    => GETLOCATIONS_LEAFLET_PATH . '/js/getlocations_leaflet_geojson.js',
  );
  if ($reset) {
    $getlocations_leaflet_paths = $defaults;
  }
  else {
    $settings = variable_get('getlocations_leaflet_paths', $defaults);
    $getlocations_leaflet_paths = getlocations_adjust_vars($defaults, $settings);
  }
  return $getlocations_leaflet_paths;
}

function getlocations_leaflet_settings_form() {

  $form = array();

  $form['rebuild'] = array(
    '#type' => 'fieldset',
    '#title' => t('Regenerate Getlocations leaflet marker cache'),
    '#description' => t('If you are having problems with markers, or have changed anything in the markers library, click on the Regenerate button.'),
  );
  $form['rebuild']['rebuild_marker_js'] = array(
    '#type' => 'submit',
    '#value' => t('Regenerate'),
    '#submit' => array('_getlocations_leaflet_rebuild_marker_js_submit'),
  );
  $form['rebuild']['getlocations_leaflet_flush'] = getlocations_element_map_checkbox(
    t('Flush marker cache'),
    variable_get('getlocations_leaflet_flush', 1),
    t('Include the marker cache when the Drupal cache is flushed.')
  );

  // cloudmade
  $getlocations_leaflet_cloudmade = variable_get('getlocations_leaflet_cloudmade', array('cloudmade_key' => '', 'cloudmade_maps' => array()));
  $form['getlocations_leaflet_cloudmade'] = array(
    '#type' => 'fieldset',
    '#title' => t('Cloudmade maps'),

    // This will store all the defaults in one variable.
    '#tree' => TRUE,
  );
  $form['getlocations_leaflet_cloudmade']['cloudmade_key'] = getlocations_element_map_tf(
    t('CloudMade Developers Key'),
    $getlocations_leaflet_cloudmade['cloudmade_key'],
    t('In order to use the <a target="_blank" href="@services">CloudMade services</a>, you must <a target="_blank" href="@key">register and get a key</a> first.', array('@services' => 'http://developers.cloudmade.com/projects', '@key' => 'http://account.cloudmade.com/register')),
    40
  );
  $mapnum = count($getlocations_leaflet_cloudmade['cloudmade_maps']);
  if ($mapnum == 0) {
    $mapnum = 2;
  }
  else {
    $mapnum++;
  }
  for ($ct = 0; $ct < $mapnum; $ct++) {
    $form['getlocations_leaflet_cloudmade']['cloudmade_maps'][$ct]['style_id'] = getlocations_element_map_tf(
      t('Style ID @num', array('@num' => $ct+1)),
      (isset($getlocations_leaflet_cloudmade['cloudmade_maps'][$ct]['style_id']) ? $getlocations_leaflet_cloudmade['cloudmade_maps'][$ct]['style_id'] : ''),
      t('The style ID for the map you want to include, see <a href="@editor">Cloudmade style editor</a>, note the number in the bottom righthand corner of the examples.', array('@editor' => 'http://maps.cloudmade.com/editor')),
      10
    );
    $form['getlocations_leaflet_cloudmade']['cloudmade_maps'][$ct]['style_name'] = getlocations_element_map_tf(
      t('Style Name @num', array('@num' => $ct+1)),
      (isset($getlocations_leaflet_cloudmade['cloudmade_maps'][$ct]['style_name']) ? $getlocations_leaflet_cloudmade['cloudmade_maps'][$ct]['style_name'] : ''),
      t('The style name for the map you want to include, it will be used in the map control. Required if you want to be able to use it.'),
      10
    );
    $form['getlocations_leaflet_cloudmade']['cloudmade_maps'][$ct]['style_description'] = getlocations_element_map_tf(
      t('Style Description @num', array('@num' => $ct+1)),
      (isset($getlocations_leaflet_cloudmade['cloudmade_maps'][$ct]['style_description']) ? $getlocations_leaflet_cloudmade['cloudmade_maps'][$ct]['style_description'] : ''),
      t('A desciption of the map style, it will be used in the map selection form.'),
      10
    );
    $form['getlocations_leaflet_cloudmade']['cloudmade_maps'][$ct]['style_token'] = getlocations_element_map_tf(
      t('Style Token @num', array('@num' => $ct+1)),
      (isset($getlocations_leaflet_cloudmade['cloudmade_maps'][$ct]['style_token']) ? $getlocations_leaflet_cloudmade['cloudmade_maps'][$ct]['style_token'] : ''),
      t('Some styles require a token.'),
      40
    );

  }

  $settings = getlocations_leaflet_defaults();

  $form['getlocations_leaflet_defaults'] = array(
    '#type' => 'fieldset',
    '#title' => t('Page settings'),
    // This will store all the defaults in one variable.
    '#tree' => TRUE,
  );
  $labels = array(
    'width' => t('Width'),
    'height' => t('Height'),
  );

  $form['getlocations_leaflet_defaults'] += getlocations_map_display_basics_form($settings, $labels);
  unset($form['getlocations_leaflet_defaults']['map_resize']);
  unset($form['getlocations_leaflet_defaults']['fullscreen_disable']);
  unset($form['getlocations_leaflet_defaults']['styles']);

  unset($form['getlocations_leaflet_defaults']['zoom']['#options']['21']);
  unset($form['getlocations_leaflet_defaults']['zoom']['#options']['20']);
  unset($form['getlocations_leaflet_defaults']['zoom']['#options']['19']);
  unset($form['getlocations_leaflet_defaults']['minzoom_map']['#options']['21']);
  unset($form['getlocations_leaflet_defaults']['minzoom_map']['#options']['20']);
  unset($form['getlocations_leaflet_defaults']['minzoom_map']['#options']['19']);

  unset($form['getlocations_leaflet_defaults']['maxzoom_map']['#options']['21']);
  unset($form['getlocations_leaflet_defaults']['maxzoom_map']['#options']['20']);
  unset($form['getlocations_leaflet_defaults']['maxzoom_map']['#options']['19']);

  $form['getlocations_leaflet_defaults'] += getlocations_leaflet_display_options_form($settings);
  unset($form['getlocations_leaflet_defaults']['nodezoom']['#options']['21']);
  unset($form['getlocations_leaflet_defaults']['nodezoom']['#options']['20']);
  unset($form['getlocations_leaflet_defaults']['nodezoom']['#options']['19']);

  $form['getlocations_leaflet_defaults']['returnlink_page_enable'] = getlocations_element_map_checkbox(
    t('Show link back to page'),
    $settings['returnlink_page_enable']
  );
  $form['getlocations_leaflet_defaults']['returnlink_page_link'] = getlocations_element_map_tf(
    t('Text of page return link'),
    $settings['returnlink_page_link'],
    t('Use %t to insert the page title'),
    30,
    64
  );

  if (module_exists('getlocations_fields')) {
    if (getlocations_check_entity_type('user') || getlocations_check_entity_type('profile2')) {
      $form['getlocations_leaflet_defaults']['returnlink_user_enable'] = getlocations_element_map_checkbox(
        t('Show link back to user'),
        $settings['returnlink_user_enable']
      );
      $form['getlocations_leaflet_defaults']['returnlink_user_link'] = getlocations_element_map_tf(
        t('Text of user return link'),
        $settings['returnlink_user_link'],
        t('Use %n to insert the user name'),
        30,
        64
      );
    }

    if (module_exists('taxonomy')) {
      if (getlocations_get_vocabularies()) {
        $form['getlocations_leaflet_defaults']['returnlink_term_enable'] = getlocations_element_map_checkbox(
          t('Show link back to term'),
          $settings['returnlink_term_enable']
        );
        $form['getlocations_leaflet_defaults']['returnlink_term_link'] = getlocations_element_map_tf(
          t('Text of term return link'),
          $settings['returnlink_term_link'],
          t('Use %n to insert the term name'),
          30,
          64
        );
      }
    }

    if (getlocations_check_entity_type('comment')) {
      $form['getlocations_leaflet_defaults']['returnlink_comment_enable'] = getlocations_element_map_checkbox(
        t('Show link back to comment'),
        $settings['returnlink_comment_enable']
      );
      $form['getlocations_leaflet_defaults']['returnlink_comment_link'] = getlocations_element_map_tf(
        t('Text of comment return link'),
        $settings['returnlink_comment_link'],
        t('Use %n to insert the comment subject'),
        30,
        64
      );
    }
  }

  // javascript paths
  $getlocations_leaflet_paths = getlocations_leaflet_paths_get();
  $form['getlocations_leaflet_paths'] = array(
    '#type' => 'fieldset',
    '#title' => t('Javascript paths'),
    '#description' => t('For advanced users who want to supply their own javascript.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    // This will store all the defaults in one variable.
    '#tree' => TRUE,
  );

  $form['getlocations_leaflet_paths']['getlocations_leaflet_path'] = getlocations_element_path(
    t('Path to Getlocations leaflet javascript file'),
    $getlocations_leaflet_paths['getlocations_leaflet_path'],
    80,
    128,
    t('Where the Getlocations leaflet javascript file is located.')
  );
  $form['getlocations_leaflet_paths']['getlocations_leaflet_circles_path'] = getlocations_element_path(
    t('Path to Getlocations leaflet circles javascript file'),
    $getlocations_leaflet_paths['getlocations_leaflet_circles_path'],
    80,
    128,
    t('Where the Getlocations leaflet circles javascript file is located.')
  );
  $form['getlocations_leaflet_paths']['getlocations_leaflet_formatter_path'] = getlocations_element_path(
    t('Path to Getlocations leaflet formatter javascript file'),
    $getlocations_leaflet_paths['getlocations_leaflet_formatter_path'],
    80,
    128,
    t('Where the Getlocations leaflet formatter javascript file is located.')
  );
  $form['getlocations_leaflet_paths']['getlocations_leaflet_polygons_path'] = getlocations_element_path(
    t('Path to Getlocations leaflet polygons javascript file'),
    $getlocations_leaflet_paths['getlocations_leaflet_polygons_path'],
    80,
    128,
    t('Where the Getlocations leaflet polygons javascript file is located.')
  );
  $form['getlocations_leaflet_paths']['getlocations_leaflet_polylines_path'] = getlocations_element_path(
    t('Path to Getlocations leaflet polylines javascript file'),
    $getlocations_leaflet_paths['getlocations_leaflet_polylines_path'],
    80,
    128,
    t('Where the Getlocations leaflet polylines javascript file is located.')
  );
  $form['getlocations_leaflet_paths']['getlocations_leaflet_rectangles_path'] = getlocations_element_path(
    t('Path to Getlocations leaflet rectangles javascript file'),
    $getlocations_leaflet_paths['getlocations_leaflet_rectangles_path'],
    80,
    128,
    t('Where the Getlocations leaflet rectangles javascript file is located.')
  );
  $form['getlocations_leaflet_paths']['getlocations_leaflet_geojson_path'] = getlocations_element_path(
    t('Path to Getlocations leaflet geojson javascript file'),
    $getlocations_leaflet_paths['getlocations_leaflet_geojson_path'],
    80,
    128,
    t('Where the Getlocations leaflet geojson javascript file is located.')
  );

  $form['getlocations_leaflet_paths']['reset'] = getlocations_element_map_checkbox(
    t('Reset'),
    0,
    t('Reset the paths to the defaults.')
  );

  unset($form['#theme']);
  $form['#theme'] = 'getlocations_leaflet_settings_form';
  $form['#validate'][] = 'getlocations_leaflet_settings_validate';
  $form['#attached']['js'] = array(GETLOCATIONS_LEAFLET_PATH . '/js/getlocations_leaflet_formatter.js' => array('type' => 'file'));

  return system_settings_form($form);

}

function getlocations_leaflet_settings_validate($form, &$form_state) {
  $reset = $form_state['values']['getlocations_leaflet_paths']['reset'];
  unset($form_state['values']['getlocations_leaflet_paths']['reset']);
  if ($reset) {
    $form_state['values']['getlocations_leaflet_paths'] = getlocations_leaflet_paths_get(TRUE);
  }

  // we need to ensure that any empty cloudmade_maps are not saved
  $mapnum = count($form_state['values']['getlocations_leaflet_cloudmade']['cloudmade_maps']);
  $emptyfound = FALSE;
  for ($ct = 0; $ct < $mapnum; $ct++) {
    if (empty($form_state['values']['getlocations_leaflet_cloudmade']['cloudmade_maps'][$ct]['style_id'])) {
      unset($form_state['values']['getlocations_leaflet_cloudmade']['cloudmade_maps'][$ct]);
      $emptyfound = TRUE;
    }
  }
  // reorder them in case some clown empties one before the last one
  if ($emptyfound) {
    $mapnum = count($form_state['values']['getlocations_leaflet_cloudmade']['cloudmade_maps']);
    $temp = array();
    $ct = 0;
    foreach ($form_state['values']['getlocations_leaflet_cloudmade']['cloudmade_maps'] AS $k => $v) {
      $temp[$ct] = $v;
      $ct++;
    }
    if (count($temp)) {
      $form_state['values']['getlocations_leaflet_cloudmade']['cloudmade_maps'] = $temp;
    }
  }

  // css check
  if (isset($form_state['values']['getlocations_leaflet_defaults']['width'])) {
    if ($check = getlocations_dim_check($form_state['values']['getlocations_leaflet_defaults']['width'])) {
      $form_state['values']['getlocations_leaflet_defaults']['width'] = $check;
    }
    else {
      form_set_error('getlocations_leaflet_defaults][width', t('Width must be valid css'));
    }
  }
  if (isset($form_state['values']['getlocations_leaflet_defaults']['height'])) {
    if ($check = getlocations_dim_check($form_state['values']['getlocations_leaflet_defaults']['height'])) {
      $form_state['values']['getlocations_leaflet_defaults']['height'] = $check;
    }
    else {
      form_set_error('getlocations_leaflet_defaults][height', t('Height must be valid css'));
    }
  }

}

/**
 * Rebuild marker js.
 */
function _getlocations_leaflet_rebuild_marker_js_submit($form, &$form_state) {
  if (getlocations_leaflet_regenerate_markers()) {
    drupal_set_message(t('Marker cache regenerated.'));
  }
}

function getlocations_leaflet_entity_type_map($type, $entity_id) {

  $entity_type = getlocations_get_entity_type_from_path($type);
  $entity_get_info = entity_get_info($entity_type);

  // get key for entity_type
  $entity_key = $entity_get_info['entity keys']['id']; // nid, cid, uid etc
  $locations = getlocations_load_locations($entity_id, $entity_key);
  $getlocations_leaflet_defaults = getlocations_leaflet_defaults();
  $settings = variable_get('getlocations_leaflet_defaults', '');
  $load_hook = $entity_get_info['load hook'];
  $object = $load_hook($entity_id);
  // marker
  $marker = $getlocations_leaflet_defaults['node_map_marker'];
  if (isset($getlocations_leaflet_defaults[$entity_type . '_map_marker'])) {
    $marker = $getlocations_leaflet_defaults[$entity_type . '_map_marker'];
  }
  $typemarkers = getlocations_get_markertypes($entity_type);
  if (isset($typemarkers[$object->type]) && $typemarkers[$object->type]) {
    $marker = $typemarkers[$object->type];
  }
  $entity_title = '';
  if (isset($object->title)) {
    $entity_title = $object->title;
  }
  elseif (isset($object->name)) {
    $entity_title = $object->name;
  }
  elseif (isset($object->subject)) {
    $entity_title = $object->subject;
  }

  $returnlink = FALSE;
  $links = array();
  // return link
  if ($entity_type == 'node' && $settings['returnlink_page_enable']) {
    if (is_object($object)) {
      $linktext = $settings['returnlink_page_link'];
      if ( preg_match("/%t/", $linktext)) {
        $linktext = preg_replace("/%t/", $object->title, $linktext);
      }
      $returnlink = l($linktext, 'node/' . $object->nid);
    }
  }
  elseif ($entity_type == 'user' && $settings['returnlink_user_enable']) {
    if (is_object($object)) {
      $linktext = $settings['returnlink_user_link'];
      if ( preg_match("/%n/", $linktext)) {
        $linktext = preg_replace("/%n/", $object->name, $linktext);
      }
      $returnlink = l($linktext, 'user/' . $object->uid);
    }
  }
  elseif (($entity_type == 'term' || $entity_type == 'taxonomy_term') && $settings['returnlink_term_enable'] && module_exists('taxonomy')) {
    if (is_object($object)) {
      $linktext = $settings['returnlink_term_link'];
      if ( preg_match("/%n/", $linktext)) {
        $linktext = preg_replace("/%n/", $object->name, $linktext);
      }
      $returnlink = l($linktext, 'taxonomy/term/' . $object->tid);
    }
  }
  elseif ($entity_type == 'comment' && $settings['returnlink_comment_enable'] && module_exists('comment')) {
    if (is_object($object)) {
      $linktext = $settings['returnlink_comment_link'];
      if ( preg_match("/%n/", $linktext)) {
        $linktext = preg_replace("/%n/", $object->subject, $linktext);
      }
      $returnlink = l($linktext, 'comment/' . $object->cid);
    }
  }
  if ($returnlink) {
    $links['returnlink'] = $returnlink;
  }

  $latlons = array();
  $minmaxes = array('minlat' => 0, 'minlon' => 0, 'maxlat' => 0, 'maxlon' => 0);
  $ct = 0;

  if (count($locations)) {
    // we should loop over them and dump bummers with no lat/lon
    foreach ($locations AS $key => $location) {
      if ($latlon = getlocations_latlon_check($location['latitude'] . ',' . $location['longitude'])) {
        $ll = explode(',', $latlon);
        $location['latitude'] = $ll[0];
        $location['longitude'] = $ll[1];
        $minmaxes = getlocations_do_minmaxes($ct, $location, $minmaxes);

        $lid = (isset($location['glid']) ? $location['glid'] : (isset($location['lid']) ? $location['lid'] : 0));

        if (! isset($location['key'])) {
          $location['key'] = '';
        }
        else {
          $location['lid'] = $entity_id;
        }
        // node only
        if ($entity_type == 'node') {
          // term markers
          $marker = getlocations_get_term_marker($entity_id, $marker);
        }

        // per location marker
        if (isset($location['marker']) && ! empty($location['marker'])) {
          $marker = $location['marker'];
        }

        if ($lid && $settings['markeraction'] == 'popup') {
          $markeraction = array('type' => 'popup', 'data' => getlocations_getinfo($lid, $entity_key));
        }
        elseif ($lid && $settings['markeraction'] == 'link') {
          $markeraction = array('type' => 'link', 'data' => getlocations_getlidinfo($lid, $entity_key));
        }
        else {
          $markeraction = array();
        }

        $name = htmlspecialchars_decode($location['name'] ? strip_tags($location['name']) : strip_tags($entity_title), ENT_QUOTES);
        $latlons[$ct] = array($location['latitude'], $location['longitude'], $entity_key, $entity_id, $lid, $entity_title, $marker, $markeraction, '');
        $iconlist[$marker] = getlocations_leaflet_get_marker($marker);

        $ct++;
      }

    } // end foreach

    if ($ct < 2 ) {
      unset($minmaxes);
      $minmaxes = '';
    }

    $map_settings = getlocations_leaflet_map_get_info('Getlocations OSM');
    $map_settings = getlocations_leaflet_get_map_layers($map_settings);

    if (! empty($settings['baselayers'])) {
      $map_layers = array();
      foreach ($settings['baselayers'] AS $k => $v) {
        if ($settings['baselayers'][$k]) {
          $map_layers[$k] = $map_settings['map_layers'][$k];
        }
      }
      if (! empty($map_layers)) {
        $map_settings['map_layers'] = $map_layers;
      }
    }

    $nodezoom = FALSE;
    if ($ct == 1 && $settings['nodezoom']) {
      $nodezoom = $settings['nodezoom'];
      $map_settings['map_opts']['center'] = array($location['latitude'], $location['longitude']);
      $map_settings['map_opts']['zoom'] = $nodezoom;
    }
    elseif ($ct < 1) {
      $ll = explode(',', $settings['latlong']);
      $map_settings['map_opts']['center'] = array($ll[0], $ll[1]);
    }

    $mapid = getlocations_setup_map('', FALSE, FALSE, TRUE);

    // add in some more
    $map_settings = getlocations_leaflet_map_settings_do($map_settings, $settings, $latlons, $mapid);
    $map_settings['map_settings']['nodezoom'] = ($nodezoom ? $nodezoom : FALSE);
    $map_settings['map_settings']['minmaxes'] = (empty($minmaxes) ? FALSE : implode(',', $minmaxes));

    $map_settings['icons'] = $iconlist;
    $map_settings['datanum'] = $ct;
    $map_settings['latlons'] = $latlons;

    if ($map_settings['map_settings']['markercluster']) {
      drupal_add_library('getlocations_leaflet', 'getlocations-leaflet-markercluster');
    }
    else {
      drupal_add_library('getlocations_leaflet', 'getlocations-leaflet');
    }
    getlocations_leaflet_js_settings_do($map_settings, $mapid);

    $output = theme('getlocations_leaflet_map', array(
      'width' => $settings['width'],
      'height' => $settings['height'],
      'map_settings' => $map_settings,
      'mapid' => $mapid,
      'links' => $links
    )
    );
    return $output;

  }

}


/**
 * Implements hook_theme().
 *
 * This lets us tell Drupal about our theme functions and their arguments.
 */
function getlocations_leaflet_theme() {

  return array(
    'getlocations_leaflet_link' => array(
      'variables' => array(
        'link_text' => '',
        'entity_type' => '',
        'entity_id' => 0,
      ),
    ),
    'getlocations_leaflet_map' => array(
      'variables' => array(
        'width' => '',
        'height' => '',
        'map_settings' => '',
        'mapid' => '',
        'links' => '',
      ),
    ),
    'getlocations_leaflet_plugin_style_options_form' => array(
      'render element' => 'form',
    ),
    'getlocations_leaflet_settings_form' => array(
      'render element' => 'form',
    ),


  );
}

function theme_getlocations_leaflet_link($variables) {
  $link_text   = $variables['link_text'];
  $entity_type = $variables['entity_type'];
  $entity_id   = $variables['entity_id'];

  $output = '';
  $path = 'getlocations_leaflet/' . $entity_type . '/' . $entity_id;
  $link = t('!l on a map', array('!l' => l($link_text, $path)));

  $output .= '<div class="getlocations_link">' . $link . '</div>';
  return $output;

}

function theme_getlocations_leaflet_map($variables) {
  drupal_add_css(GETLOCATIONS_LEAFLET_PATH . '/getlocations_leaflet.css');
  $width = $variables['width'];
  $height = $variables['height'];
  $map_settings = $variables['map_settings'];
  $mapid = $variables['mapid'];
  $links = $variables['links'];

  $output = '';

  // links
  if (isset($links['returnlink'])) {
    $output .= '<div class="getlocations_returnlink">' . $links['returnlink'] . '</div>';
  }

  // wrap the map
  $output .= '<div id="getlocations_leaflet_wrapper_' . $mapid . '"  style="width: ' . $width . '; height: ' . $height . '" >';
  $output .= '<div class="getlocations_leaflet_canvas" id="getlocations_leaflet_canvas_' . $mapid . '" style="width: 100%; height: 100%" ></div>';
  $output .= '</div>';

  return $output;

}

function theme_getlocations_leaflet_plugin_style_options_form($variables) {
  $form = $variables['form'];
  $output = '';

  $output .= drupal_render_children($form);
  return $output;
}

function theme_getlocations_leaflet_settings_form($variables) {
  $form = $variables['form'];
  $output = '';
  $form['getlocations_leaflet_defaults']['returnlink_page_link']['#prefix'] = '<div id="wrap-page-link">';
  $form['getlocations_leaflet_defaults']['returnlink_page_link']['#suffix'] = '</div>';
  if (isset($form['getlocations_leaflet_defaults']['returnlink_user_link'])) {
    $form['getlocations_leaflet_defaults']['returnlink_user_link']['#prefix'] = '<div id="wrap-user-link">';
    $form['getlocations_leaflet_defaults']['returnlink_user_link']['#suffix'] = '</div>';
  }
  if (isset($form['getlocations_leaflet_defaults']['returnlink_term_link'])) {
    $form['getlocations_leaflet_defaults']['returnlink_term_link']['#prefix'] = '<div id="wrap-term-link">';
    $form['getlocations_leaflet_defaults']['returnlink_term_link']['#suffix'] = '</div>';
  }
  if (isset($form['getlocations_leaflet_defaults']['returnlink_comment_link'])) {
    $form['getlocations_leaflet_defaults']['returnlink_comment_link']['#prefix'] = '<div id="wrap-comment-link">';
    $form['getlocations_leaflet_defaults']['returnlink_comment_link']['#suffix'] = '</div>';
  }

  $output .= drupal_render_children($form);
  return $output;
}
