<?php

/**
 * @file
 * @author Bob Hutchinson http://drupal.org/user/52366
 * @copyright GNU GPL
 *
 * Provides a search page.
 * for Drupal 7
 */

define('GETLOCATIONS_SEARCH_PATH', drupal_get_path('module', 'getlocations_search'));

/**
 * Implements hook_help().
 */
function getlocations_search_help($path, $arg) {
  switch ($path) {
    case 'admin/help#getlocations_search':
      $output = '<p>' . t('Provide a search faciliy for locations on a map.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function getlocations_search_menu() {
  $items = array();

  $items['admin/config/services/getlocations_search'] = array(
    'title' => 'Getlocations search',
    'description' => 'Configure Getlocations search',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('getlocations_search_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'getlocations_search.admin.inc',
  );

  $items['getlocations_search'] = array(
    'title' => 'Getlocations search',
    'access arguments' => array('access getlocations'),
    'page callback' => 'getlocations_search',
    'type' => MENU_SUGGESTED_ITEM,
  );
  // getlocations_search/info     # ajax callback to fetch all location info
  $items['getlocations_search/info'] = array(
    'page callback' => 'getlocations_search_allinfo',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  if (module_exists('taxonomy')) {
    $items['getlocations_search/term_autocomplete'] = array(
      'page callback' => 'getlocations_search_term_autocomplete',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );
  }

  return $items;
}

/**
 * Menu item
 */
function getlocations_search() {
  $contents = '';
  $form = drupal_get_form('getlocations_search_form');
  $contents .= drupal_render($form);

  $map = getlocations_search_getmap();
  $contents .= $map;

  return $contents;
}

/**
 * The search form
 *
 */
function getlocations_search_form($form, &$form_state) {
  $getlocations_search_defaults = getlocations_search_defaults();

  $form['#attached']['css'] = array(GETLOCATIONS_SEARCH_PATH . '/getlocations_search.css');
  if ($getlocations_search_defaults['method'] == 'vocab' && $getlocations_search_defaults['vocab_element'] == 'dropdown') {
    //
    $form['getlocations_search'] = array(
      '#type' => 'select',
      '#title' => t('Search'),
      '#options' => getlocations_search_term_get(),
    );
  }
  else {
    $form['getlocations_search'] = array(
      '#type' => 'textfield',
      '#title' => t('Search'),
      '#maxlength' => 255,
      '#size' => 50,
    );
    if ($getlocations_search_defaults['method'] == 'vocab' && $getlocations_search_defaults['vocab_element'] == 'autocomplete') {
      $form['getlocations_search']['#autocomplete_path'] = 'getlocations_search/term_autocomplete';
    }
  }

  if ($getlocations_search_defaults['use_geolocation_button']) {
    $form['getlocations_search_geolocation_button'] = array(
      '#markup' => '',
    );
  }

  if ($getlocations_search_defaults['display_search_distance']) {
    $form['getlocations_search_distance'] = getlocations_element_search_distance($getlocations_search_defaults['search_distance'], t('Search distance'), t('The distance away from the center to search for locations.'));
  }
  else {
    $form['getlocations_search_distance'] = array(
      '#type' => 'hidden',
      '#value' => $getlocations_search_defaults['search_distance'],
      '#attributes' => array('id' => 'edit-getlocations-search-distance')
    );
  }

  if ($getlocations_search_defaults['display_search_units']) {
    $form['getlocations_search_units'] = getlocations_element_distance_unit($getlocations_search_defaults['search_units'], t('Distance units'));
  }
  else {
    $form['getlocations_search_units'] = array(
      '#type' => 'hidden',
      '#value' => $getlocations_search_defaults['search_units'],
      '#attributes' => array('id' => 'edit-getlocations-search-units')
    );
  }

  if ($getlocations_search_defaults['display_search_limits']) {
    $form['getlocations_search_limits'] = getlocations_element_map_limits($getlocations_search_defaults['search_limits']);
  }
  else {
    $form['getlocations_search_limits'] = array(
      '#type' => 'hidden',
      '#value' => $getlocations_search_defaults['search_limits'],
      '#attributes' => array('id' => 'edit-getlocations-search-limits')
    );
  }

  if ($getlocations_search_defaults['display_search_type']) {
    $opts = array('all' => t('Show All'), 'node' => t('Nodes'));
    if (user_access('access user getlocations')) {
      $opts['user'] = t('Users');
    }
    if (module_exists('taxonomy')) {
      $opts['term'] = t('Terms');
    }
    if (user_access('access comments') && module_exists('comment')) {
      $opts['comment'] = t('Comments');
    }
    $form['getlocations_search_type'] = array(
      '#type' => 'select',
      '#title' => t('Restrict the search'),
      '#options' => $opts,
      '#default_value' => $getlocations_search_defaults['search_type'],
      '#description' => t('Restrict the search to a content type'),
    );

  }
  else {
    $form['getlocations_search_type'] = array(
      '#type' => 'hidden',
      '#value' => $getlocations_search_defaults['search_type'],
      '#attributes' => array('id' => 'edit-getlocations-search-type')
    );
  }

  if ($getlocations_search_defaults['method'] != 'google_ac') {
    $form['getlocations_search_submit'] = array(
      '#type' => 'submit',
      '#value' => t('Go')
    );
  }

  return $form;
}

/**
 * Set up the map and use getlocations to spit it out
 *
 */
function getlocations_search_getmap() {
  $getlocations_defaults = getlocations_defaults();
  $getlocations_defaults['places'] = 1;
  $getlocations_defaults['preload_data'] = 0;

  $getlocations_search_defaults = getlocations_search_defaults();

  // we need a markermanager enabled
  if ($getlocations_defaults['markermanagertype'] < 1) {
    $getlocations_search_defaults['markermanagertype'] = 1;
  }
  $getlocations_search_defaults['pansetting'] = $getlocations_defaults['pansetting'];

  // we need to update $getlocations_defaults with data from $getlocations_search_defaults
  $keys = array('width', 'height', 'styles', 'latlong', 'zoom', 'controltype', 'pancontrol', 'mtc', 'maptype', 'baselayers', 'behavior', 'draggable', 'streetview_show', 'trafficinfo', 'bicycleinfo', 'panoramio_use', 'poi_show', 'transit_show', 'minzoom', 'maxzoom', 'nodezoom', 'markermanagertype', 'usemarkermanager', 'useclustermanager', 'markerclusterer_style', 'markerclusterer_zoom', 'markerclusterer_size', 'markerclusterer_minsize', 'markerclusterer_title', 'markeraction', 'markeractiontype', 'weather_show');
  foreach ($keys AS $key) {
    $getlocations_defaults[$key] = $getlocations_search_defaults[$key];
  }

  #if ($getlocations_search_defaults['use_geolocation_button']) {
  #  $getlocations_defaults['use_jsapi'] = 1;
  #}
  $mapid = getlocations_setup_map($getlocations_defaults);

  getlocations_search_js_settings_do($getlocations_search_defaults, $mapid);
  $getlocations_search_paths = variable_get('getlocations_search_paths', array('getlocations_search_path' => GETLOCATIONS_SEARCH_PATH . '/js/getlocations_search.js'));
  $jsfile = $getlocations_search_paths['getlocations_search_path'];
  drupal_add_js($jsfile);

  $minmaxes = '';
  #$lla = explode(',', $getlocations_search_defaults['latlong']);
  #$latlons[] = array($lla[0], $lla[1], 0, '', $getlocations_search_defaults['search_map_marker'], '');
  $latlons = array();
  getlocations_js_settings_do($getlocations_defaults, $latlons, $minmaxes, $mapid, FALSE, TRUE);

  $map = theme('getlocations_show', array('width' => $getlocations_defaults['width'] , 'height' => $getlocations_defaults['height'] , 'defaults' => $getlocations_defaults, 'mapid' => $mapid, 'type' => '', 'node' => ''));
  return $map;
}

/**
 * @param array $defaults
 *  Settings
 *
 * @param string $mapid
 *  Unique map identifier used in javascript to allow multiple maps
 *
 */
function getlocations_search_js_settings_do($defaults, $mapid) {

  $do_lookup = getlocations_search_do_types();
  $settings = array(
    $mapid => array(
      'method' => $defaults['method'],
      'maxzoom' => $defaults['maxzoom'],
      'do_lookup' => ($do_lookup ? 1 : 0),
    ),
  );

  drupal_add_js(array('getlocations_search' => $settings), 'setting');
}



/**
 * Implements hook_theme().
 *
 * This lets us tell Drupal about our theme functions and their arguments.
 */
function getlocations_search_theme() {
  return array(
    'getlocations_search_form' => array(
      'render element' => 'form',
    ),
    'getlocations_search_settings_form' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Themes the search form and results.
 *
 * @param array $variables
 *
 * @return
 *   Returns $output
 *
 */
function theme_getlocations_search_form($variables) {
  $form = $variables['form'];
  $output = '';
  $form['getlocations_search']['#prefix'] = '<div id="getlocations_search_wrapper">';
  $form['getlocations_search_submit']['#suffix'] = '</div>';

  if (getlocations_is_mobile() && isset($form['getlocations_search_geolocation_button'])) {
    $geolocation_button = '<p><input type="submit" value="' . t('Find current Location') . '" title="' . t('Get the latitude and longitude for this location from the browser') . '" id="getlocations_search_geolocation_button" class="form-submit" />&nbsp;<span id="getlocations_search_geolocation_status" ></span></p>';
    $geolocation_button .= '<p>Use the browser to find your current location</p>';
    $form['getlocations_search_geolocation_button']['#markup'] = $geolocation_button;
  }

  $output .= drupal_render_children($form);

  $output .= '<div id="getlocations_search_result">';
  $output .= '<h4>' . t('Results') . '</h4>';
  $output .= '<div id="getlocations_search_address"></div>';
  $output .= '<div id="getlocations_search_distance"></div>';
  $output .= '<div id="getlocations_search_count"></div>';
  $output .= '<div id="getlocations_search_type"></div>';
  $output .= '<div id="getlocations_search_latlon_wrapper">';
  $output .= '<div id="getlocations_search_lat"></div>';
  $output .= '<div id="getlocations_search_lon"></div>';
  $output .= '</div>';
  $output .= '</div>';
  return $output;
}

/**
 * Themes getlocations_search settings form
 *
 * @param array $variables
 *
 * @return
 *   Returns $output
 *
 */
function theme_getlocations_search_settings_form($variables) {
  $form = $variables['form'];
  $output = '';

  if (isset($form['getlocations_search_defaults']['vocab']) ) {
    $form['getlocations_search_defaults']['vocab']['#prefix'] = '<div id="getlocations_search_defaults_vocab">';
    $form['getlocations_search_defaults']['vocab_element']['#suffix'] = '</div>';
  }
  $form['getlocations_search_defaults']['useclustermanager']['#prefix'] = '<div id="wrap-getlocations-clusteropts">';
  $form['getlocations_search_defaults']['markerclusterer_minsize']['#suffix'] = '</div>';

#  if (module_exists('colorbox')) {
#    $getlocations_colorbox = getlocations_colorbox_settings();
#    if ($getlocations_colorbox['marker_enable']) {
#      $link = getlocations_markerpicker_link($form['getlocations_search_defaults']['search_map_marker']['#id'], 's');
#      $form['getlocations_search_defaults']['search_map_marker']['#field_suffix'] = '&nbsp;' . $link;
#    }
#  }

  $output .= drupal_render_children($form);
  return $output;

}

/**
 * Set up default settings.
 *
 * @return array $newdefaults
 *
 */
function getlocations_search_defaults() {
  $getlocations_defaults = getlocations_defaults();
  $defaults = array(
    'method' => 'google_ac',
    'vocab' => '',
    'vocab_element' => 'dropdown',
    'search_map_marker' => 'drupal',
    'search_distance' => 1,
    'search_units' => 'km',
    'search_limits' => 0,
    'search_type' => 'all',
    'display_dms' => 0,
    'display_search_distance' => 1,
    'display_search_units' => 1,
    'display_search_limits' => 1,
    'display_search_type' => 1,
    'width'                     => $getlocations_defaults['width'],
    'height'                    => $getlocations_defaults['height'],
    'styles'                    => $getlocations_defaults['styles'],
    'latlong'                   => $getlocations_defaults['latlong'],
    'zoom'                      => $getlocations_defaults['zoom'],
    'controltype'               => $getlocations_defaults['controltype'],
    'pancontrol'                => $getlocations_defaults['pancontrol'],
    'mtc'                       => $getlocations_defaults['mtc'],
    'maptype'                   => $getlocations_defaults['maptype'],
    'baselayers' => array(
      'Map'                     => $getlocations_defaults['baselayers']['Map'],
      'Satellite'               => $getlocations_defaults['baselayers']['Satellite'],
      'Hybrid'                  => $getlocations_defaults['baselayers']['Hybrid'],
      'Physical'                => $getlocations_defaults['baselayers']['Physical'],
    ),
    'behavior' => array(
      'scale'                   => $getlocations_defaults['behavior']['scale'],
      'overview'                => $getlocations_defaults['behavior']['overview'],
      'overview_opened'         => $getlocations_defaults['behavior']['overview_opened'],
      'scrollwheel'             => $getlocations_defaults['behavior']['scrollwheel'],
    ),
    'draggable'                 => $getlocations_defaults['draggable'],
    'streetview_show'           => $getlocations_defaults['streetview_show'],
    'trafficinfo'               => $getlocations_defaults['trafficinfo'],
    'bicycleinfo'               => $getlocations_defaults['bicycleinfo'],
    'panoramio_use'             => $getlocations_defaults['panoramio_use'],
    'poi_show'                  => $getlocations_defaults['poi_show'],
    'transit_show'              => $getlocations_defaults['transit_show'],
    'markeraction'              => $getlocations_defaults['markeraction'],
    'markeractiontype'          => $getlocations_defaults['markeractiontype'],
    'minzoom'                   => $getlocations_defaults['minzoom'],
    'maxzoom'                   => $getlocations_defaults['maxzoom'],
    'nodezoom'                  => $getlocations_defaults['nodezoom'],
    'markermanagertype'         => $getlocations_defaults['markermanagertype'],
    'usemarkermanager'          => $getlocations_defaults['usemarkermanager'],
    'useclustermanager'         => $getlocations_defaults['useclustermanager'],
    'markerclusterer_style'     => $getlocations_defaults['markerclusterer_style'],
    'markerclusterer_zoom'      => $getlocations_defaults['markerclusterer_zoom'],
    'markerclusterer_size'      => $getlocations_defaults['markerclusterer_size'],
    'markerclusterer_minsize'   => $getlocations_defaults['markerclusterer_minsize'],
    'markerclusterer_title'     => $getlocations_defaults['markerclusterer_title'],
    'pansetting'                => $getlocations_defaults['pansetting'],
    'use_geolocation_button'    => $getlocations_defaults['use_jsapi'],
    'weather_use'               => $getlocations_defaults['weather_use'],
    'weather_show'              => $getlocations_defaults['weather_show'],
  );

  $settings = variable_get('getlocations_search_defaults', $defaults);
  $getlocations_search_defaults = getlocations_adjust_vars($defaults, $settings);
  return $getlocations_search_defaults;

}

/**
 * @return array $options
 *   Returns list of vocabularies suitable for a dropdown
 */
function getlocations_search_get_vocabularies() {
  if (module_exists('taxonomy')) {
    $vocabularies = taxonomy_get_vocabularies();
    $options = array();
    if (count($vocabularies)) {
      foreach ($vocabularies as $vid => $vocabulary) {
        $options[$vid] = $vocabulary->name;
      }
      return $options;
    }
  }
  return FALSE;
}

/**
 * autocomplete for taxonomy terms
 *
 * @param string $string
 *
 * @return
 *   Returns term names
 *
 */
function getlocations_search_term_autocomplete($string) {
  $matches = array();

  // Taxonomy which holds locative info
  $getlocations_search_defaults = getlocations_search_defaults();
  $vid = FALSE;
  if (is_numeric($getlocations_search_defaults['vocab']) && $getlocations_search_defaults['vocab'] > 0) {
    $vid = $getlocations_search_defaults['vocab'];
  }

  if ($vid) {
    $query = db_select('taxonomy_term_data', 't');
    $query->fields('t', array('name'))
     ->where("LOWER(name) LIKE LOWER(:st)", array(':st' => $string . '%'))
     ->condition('t.vid', $vid, '=')
      ->range(0, 15);
    $result = $query->execute();
    foreach ($result AS $row) {
      $matches[$row->name] = check_plain($row->name);
    }
  }
  drupal_json_output($matches);
}

/**
 * @return array $matches
 *   Returns a list of terms of a given vocabulary, suitable for a dropdown
 */
function getlocations_search_term_get() {
  $matches = array();

  // Taxonomy which holds locative info
  $getlocations_search_defaults = getlocations_search_defaults();
  $vid = FALSE;
  if (is_numeric($getlocations_search_defaults['vocab']) && $getlocations_search_defaults['vocab'] > 0) {
    $vid = $getlocations_search_defaults['vocab'];
  }

  if ($vid) {
    $query = db_select('taxonomy_term_data', 't');
    $query->fields('t', array('name'))
     ->condition('t.vid', $vid, '=');
    $result = $query->execute();
    foreach ($result AS $row) {
      $matches[$row->name] = getlocations_apoclean($row->name);
    }
  }
  ksort($matches);
  return $matches;
}

/**
 * @return json format $output
 *   Returns search result to getlocations_search.js
 *
 */
function getlocations_search_allinfo() {
  $lat = $_GET['lat'];
  $lon = $_GET['lon'];
  $getlocations_search_defaults = getlocations_search_defaults();
  $distance = $getlocations_search_defaults['search_distance'];
  if (isset($_GET['distance']) && is_numeric($_GET['distance'])) {
    $distance = $_GET['distance'];
    // sanity check
    if ($distance < 1) {
      $distance = $getlocations_search_defaults['search_distance'];
    }
  }
  $units = $getlocations_search_defaults['search_units'];
  if (isset($_GET['units'])) {
    $units = $_GET['units'];
    // sanity check
    $unitsarr = array('km', 'm', 'mi', 'yd', 'nmi');
    if (! in_array($units, $unitsarr)) {
      $units = $getlocations_search_defaults['search_units'];
    }
  }
  $type = $getlocations_search_defaults['search_type'];
  if (isset($_GET['type'])) {
    $type = $_GET['type'];
    // sanity check
    $typarr = array('all', 'node', 'user', 'term', 'comment');
    if (! in_array($type, $typarr)) {
      $type = $getlocations_search_defaults['search_type'];
    }
  }

  $dosort = FALSE;
  if (isset($_GET['limits']) && is_numeric($_GET['limits'])) {
    $limits = $_GET['limits'];
    // sanity check
    if ($limits < 0) {
      $limits = 0;
    }
    if ($limits > 0) {
      $dosort = TRUE;
    }
  }

  $dms = ($getlocations_search_defaults['display_dms'] ? TRUE : FALSE);
  // sanity check
  $latlon = $lat . ',' . $lon;
  if (getlocations_latlon_check($latlon)) {
    $output = getlocations_search_info_sql($lat, $lon, $distance, $units, $type, $dosort, $limits, $dms);
    drupal_json_output($output);
  }
}

// $type can be node, user, comment, term. anything else is all
function getlocations_search_info_sql($lat, $lon, $distance, $units, $type, $dosort, $limits, $dms) {

  $getlocations_defaults = getlocations_defaults();

  $distance_meters = getlocations_convert_distance_to_meters($distance, $units);
  $latrange = getlocations_earth_latitude_range($lat, $lon, $distance_meters);
  $lonrange = getlocations_earth_longitude_range($lat, $lon, $distance_meters);

  $locations = array();

  if (module_exists('getlocations_fields')) {
    if ($lonrange[0] > $lonrange[1]) {
      $where = "g.latitude > :minlat AND g.latitude < :maxlat AND ((g.longitude < 180 AND g.longitude > :minlon) OR (g.longitude < :maxlon AND g.longitude > -180))";
    }
    else {
      $where = "g.latitude > :minlat AND g.latitude < :maxlat AND g.longitude > :minlon AND g.longitude < :maxlon";
    }
    $sqlarr = array(':minlat' => $latrange[0], ':maxlat' => $latrange[1], ':minlon' => $lonrange[0], ':maxlon' => $lonrange[1]);

    $fields = array();
    $fields[] = 'g.glid';
    $fields[] = 'g.name';
    $fields[] = 'g.latitude';
    $fields[] = 'g.longitude';
    $fields[] = 'g.marker';

    $fields[] = 'f.nid';
    $fields[] = 'f.uid';
    $fields[] = 'f.tid';
    $fields[] = 'f.cid';

    $sqlsnip1 = "";
    $sqlsnip2 = "";
    $marker = '';
    if ($type == 'node' && user_access('access content') && user_access('access getlocations')) {
      $fields[] = 'n.title AS title';
      $fields[] = 'n.nid';
      $sqlsnip1 = "LEFT JOIN {node} n ON f.vid = n.vid ";
      $sqlsnip2 = "AND n.nid > 0 ";
      $marker = $getlocations_defaults['node_map_marker'];
    }
    elseif ($type == 'user' && getlocations_access_user_location()) {
      $fields[] = 'u.name AS title';
      $fields[] = 'u.uid';
      $sqlsnip1 = "LEFT JOIN {users} u ON f.uid = u.uid ";
      $sqlsnip2 = "AND u.uid > 0 ";
      $marker = $getlocations_defaults['user_map_marker'];
    }
    elseif ($type == 'term' && user_access('access getlocations')) {
      $fields[] = 't.name AS title';
      $fields[] = 't.tid';
      $sqlsnip1 = "LEFT JOIN {taxonomy_term_data} t ON f.tid = t.tid ";
      $sqlsnip2 = "AND t.tid > 0 ";
      $marker = $getlocations_defaults['vocabulary_map_marker'];
    }
    elseif ($type == 'comment' && user_access('access comments') && user_access('access getlocations')) {
      $fields[] = 'c.subject AS title';
      $fields[] = 'c.cid';
      $sqlsnip1 = "LEFT JOIN {comment} c ON f.cid = c.cid ";
      $sqlsnip2 = "AND c.cid > 0 ";
      $marker = $getlocations_defaults['comment_map_marker'];
    }
    elseif ($type == 'all') {
      $sqlsnip2arr = array();
      if (user_access('access content') && user_access('access getlocations')) {
        $sqlsnip2arr[] = "f.nid > 0";
        $sqlsnip2arr[] = "f.tid > 0";
      }
      if (getlocations_access_user_location()) {
        $sqlsnip2arr[] = "f.uid > 0";
      }
      if (user_access('access comments') && user_access('access getlocations')) {
        $sqlsnip2arr[] = "f.cid > 0";
      }
      if (! empty($sqlsnip2arr)) {
        $sqlsnip2 = "AND (" . implode(" OR ", $sqlsnip2arr) . ") ";
      }
      else {
        // this user may not see anything
        $sqlsnip2 = "AND 1=0 ";
      }
    }

    if ($dosort) {
      $sort = getlocations_earth_distance_sql($lat, $lon, 'g');
      $fields[] = "$sort AS distance_sort ";
    }

    $selects = implode(",", $fields);

    $sql = "SELECT $selects ";
    $sql .= "FROM {getlocations_fields} g LEFT JOIN {getlocations_fields_entities} f ON g.glid = f.glid ";
    $sql .= $sqlsnip1;
    $sql .= "WHERE ($where) ";
    $sql .= "AND g.glid IS NOT NULL ";
    $sql .= "AND g.latitude != '0' ";
    $sql .= "AND g.longitude != '0' ";
    $sql .= $sqlsnip2;
    if ($dosort) {
      $sql .= "ORDER BY distance_sort ASC ";
    }
    if ($limits > 0) {
      $sql .= "LIMIT 0, $limits ";
    }

    $result = db_query($sql, $sqlarr);
    foreach ($result AS $k => $row) {
      $locations[$k] = $row;
      if (empty($locations[$k]->marker)) {
        if (! empty($marker)) {
          $locations[$k]->marker = $marker;
        }
        else {
          // must be an 'all' search so we have to figure out a marker
          if ($locations[$k]->nid > 0) {
            $locations[$k]->marker = $getlocations_defaults['node_map_marker'];

            // term markers
            $locations[$k]->marker = getlocations_get_term_marker($locations[$k]->nid, $locations[$k]->marker);

          }
          elseif ($locations[$k]->uid > 0) {
            $locations[$k]->marker = $getlocations_defaults['user_map_marker'];
          }
          elseif ($locations[$k]->tid > 0) {
            $locations[$k]->marker = $getlocations_defaults['vocabulary_map_marker'];
          }
          elseif ($locations[$k]->cid > 0) {
            $locations[$k]->marker = $getlocations_defaults['comment_map_marker'];
          }
        }
      }
    }

  } // getlocations_fields sql
  elseif (module_exists('geolocation')) {
    $module = 'geolocation';
    $gtype = 'geolocation_latlng';
    $entity_type = '';
    $fieldnames = getlocations_other_get_fieldname($gtype, $module, $entity_type);
    if (! empty($fieldnames)) {
      $tabledata = array();
      $ct = 0;
      foreach ($fieldnames AS $fieldname) {
        $tabledata[$ct]['table'] = 'field_data_' . $fieldname;
        $tabledata[$ct]['fieldname_latitude'] = $fieldname . '_lat';
        $tabledata[$ct]['fieldname_longitude'] = $fieldname . '_lng';
        $ct++;
      }
    }
  }
  elseif (module_exists('geofield')) {
    $module = 'geofield';
    $gtype = 'geofield';
    $entity_type = '';
    $fieldnames = getlocations_other_get_fieldname($gtype, $module, $entity_type);
    if (! empty($fieldnames)) {
      $tabledata = array();
      $ct = 0;
      foreach ($fieldnames AS $fieldname) {
        $tabledata[$ct]['table'] = 'field_data_' . $fieldname;
        $tabledata[$ct]['fieldname_latitude'] = $fieldname . '_lat';
        $tabledata[$ct]['fieldname_longitude'] = $fieldname . '_lon';
        $ct++;
      }
    }
  }
  if ((module_exists('geolocation') || module_exists('geofield')) && ! empty($fieldnames)) {
    //
    $location_ct = 0;
    foreach ($tabledata AS $data) {
      $table = $data['table'];
      $latfield = 'g.' . $data['fieldname_latitude'];
      $lonfield = 'g.' . $data['fieldname_longitude'];
      if ($lonrange[0] > $lonrange[1]) {
        $where = "$latfield > :minlat AND $latfield < :maxlat AND (($lonfield < 180 AND $lonfield > :minlon) OR ($lonfield < :maxlon AND $lonfield > -180))";
      }
      else {
        $where = "$latfield > :minlat AND $latfield < :maxlat AND $lonfield > :minlon AND $lonfield < :maxlon";
      }
      $sqlarr = array(':minlat' => $latrange[0], ':maxlat' => $latrange[1], ':minlon' => $lonrange[0], ':maxlon' => $lonrange[1]);

      $fields = array();
      $fields[] = "$latfield AS latitude";
      $fields[] = "$lonfield AS longitude";
      $fields[] = "g.entity_type AS entity_type";
      $fields[] = "g.entity_id AS entity_id";

      $sqlsnip1 = "";
      $sqlsnip2 = "";
      $marker = '';
      if ($type == 'node' && user_access('access content') && user_access('access getlocations')) {
        $fields[] = 'n.title AS title';
        $fields[] = 'n.nid';
        $sqlsnip1 = "LEFT JOIN {node} n ON g.entity_id = n.nid ";
        $sqlsnip2 = "AND g.entity_type = :type AND n.nid > 0 ";
        $sqlarr[':type'] = $type;
        $marker = $getlocations_defaults['node_map_marker'];
      }
      elseif ($type == 'user' && getlocations_access_user_location()) {
        $fields[] = 'u.name AS title';
        $fields[] = 'u.uid';
        $sqlsnip1 = "LEFT JOIN {users} u ON g.entity_id = u.uid ";
        $sqlsnip2 = "AND g.entity_type = :type AND u.uid > 0 ";
        $sqlarr[':type'] = $type;
        $marker = $getlocations_defaults['user_map_marker'];
      }
      elseif ($type == 'term' && user_access('access getlocations')) {
        $fields[] = 't.name AS title';
        $fields[] = 't.tid';
        $sqlsnip1 = "LEFT JOIN {taxonomy_term_data} t ON g.entity_id = t.tid ";
        $sqlsnip2 = "AND g.entity_type = :type AND t.tid > 0 ";
        $sqlarr[':type'] = $type;
        $marker = $getlocations_defaults['vocabulary_map_marker'];
      }
      elseif ($type == 'comment' && user_access('access comments') && user_access('access getlocations')) {
        $fields[] = 'c.subject AS title';
        $fields[] = 'c.cid';
        $sqlsnip1 = "LEFT JOIN {comment} c ON g.entity_id = c.cid ";
        $sqlsnip2 = "AND g.entity_type = :type AND c.cid > 0 ";
        $sqlarr[':type'] = $type;
        $marker = $getlocations_defaults['comment_map_marker'];
      }
      elseif ($type == 'all') {
        // need a list of all the entity_types in this table so that we can limit on permissions
        $sqlsnip2arr = array();
        $permitted_entity_types = array();
        if (user_access('access content') && user_access('access getlocations')) {
          $permitted_entity_types[] = 'node';
        }
        if (getlocations_access_user_location()) {
          $permitted_entity_types[] = 'user';
        }
        if (user_access('access getlocations')) {
          $permitted_entity_types[] = 'term';
        }
        if (user_access('access comments') && user_access('access getlocations')) {
          $permitted_entity_types[] = 'comment';
        }

        $sql = "SELECT DISTINCT entity_type FROM {$table} ";
        $rows = db_query($sql);
        $at = '';
        $ct = 1;
        $sqlsnip2 = '';
        foreach ($rows AS $row) {
          $et = $row->entity_type;
          if (in_array($et, $permitted_entity_types)) {
            $sqlsnip2arr[] = "g.entity_type = :et_$ct";
            $sqlarr[":et_$ct"] = $et;
            $ct++;
          }
        }
        if (! empty($sqlsnip2arr)) {
          $sqlsnip2 = "AND (" . implode(" OR ", $sqlsnip2arr) . ") ";
        }
        else {
          // this user may not see anything
          $sqlsnip2 = "AND 1=0 ";
        }
      }

      if ($dosort) {
        $sort = getlocations_earth_distance_sql($lat, $lon, 'g');
        $fields[] = "$sort AS distance_sort ";
      }

      $selects = implode(",", $fields);

      $sql = "SELECT $selects FROM {$table} g ";
      $sql .= $sqlsnip1;
      $sql .= "WHERE ($where) ";
      $sql .= "AND $latfield != '0' ";
      $sql .= "AND $lonfield != '0' ";
      $sql .= $sqlsnip2;
      if ($dosort) {
        $sql .= "ORDER BY distance_sort ASC ";
      }
      if ($limits > 0) {
        $sql .= "LIMIT 0, $limits ";
      }

      $result = db_query($sql, $sqlarr);
      foreach ($result AS $row) {
        $locations[$location_ct]->latitude = $row->latitude;
        $locations[$location_ct]->longitude = $row->longitude;
        $locations[$location_ct]->title = $row->title;
        if ($row->entity_type == 'node') {
          $locations[$location_ct]->nid = $row->entity_id;
          $locations[$location_ct]->marker = $getlocations_defaults['node_map_marker'];

          // term markers
          $locations[$location_ct]->marker = getlocations_get_term_marker($row->entity_id, $locations[$location_ct]->marker);

        }
        elseif ($row->entity_type == 'user') {
          $locations[$location_ct]->uid = $row->entity_id;
          $locations[$location_ct]->marker = $getlocations_defaults['user_map_marker'];
        }
        elseif ($row->entity_type == 'term') {
          $locations[$location_ct]->tid = $row->entity_id;
          $locations[$location_ct]->marker = $getlocations_defaults['vocabulary_map_marker'];
        }
        elseif ($row->entity_type == 'comment') {
          $locations[$location_ct]->cid = $row->entity_id;
          $locations[$location_ct]->marker = $getlocations_defaults['comment_map_marker'];
        }

        $location_ct++;
      }
    }
  }

  $minmaxes = $latrange[0] . ',' . $lonrange[0] . ',' . $latrange[1] . ',' . $lonrange[1];
  // format lat/lon
  if ($dms) {
    $latout = theme('getlocations_latitude_dms', array('latitude' => $lat));
    $lonout = theme('getlocations_longitude_dms', array('longitude' => $lon));
  }
  else {
    $latout = round($lat, 6);
    $lonout = round($lon, 6);
  }
  $infoarr = array($distance, $units, ($type ? $type : 'all'), $latout, $lonout);
  $info = implode(",", $infoarr);
  $ret = array('locations' => $locations, 'minmaxes' => $minmaxes, 'info' => $info);

  return $ret;

}

function getlocations_search_do_types() {
  $return = FALSE;
  if (module_exists('getlocations_fields')) {
    $return = TRUE;
  }
  elseif (module_exists('geolocation')) {
    $return = TRUE;
  }
  elseif (module_exists('geofield')) {
    $return = TRUE;
  }

  return $return;
}
